#!/usr/bin/env python3
"""Directory mining results — adds new companies to the queue."""
import json
import datetime

QUEUE = '/Users/corgi12/.eragon-joshua_augustine/joshua_augustine_workspace/jordan.ai/overnight/shared/new_companies_queue.jsonl'

# Load existing domains for dedup
existing = set()
with open(QUEUE) as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                d = json.loads(line)
                existing.add(d.get('domain', '').lower().strip())
            except:
                pass

print(f"Existing domains: {len(existing)}")

# All companies discovered from mining
# Format: (domain, name, source, description)
RAW_COMPANIES = [

    # ========== TinySeed Portfolio ==========
    ("ipos.shop", "iPos", "TinySeed", "Point of sale SaaS"),
    ("giantrocketship.com", "Giant Rocketship", "TinySeed", "SaaS analytics"),
    ("askedgar.io", "Ask Edgar", "TinySeed", "Social media scheduling SaaS"),
    ("bluelightmaps.com", "Blue Light Maps", "TinySeed", "Local maps SaaS"),
    ("cargofax.co", "CargoFax", "TinySeed", "Freight/logistics SaaS"),
    ("hothawk.ai", "Hot Hawk AI", "TinySeed", "AI sales SaaS"),
    ("getinboxzero.com", "Inbox Zero", "TinySeed", "Email productivity SaaS"),
    ("leadtruffle.com", "Lead Truffle", "TinySeed", "Lead gen SaaS"),
    ("outboundlegal.com", "Outbound Legal", "TinySeed", "Legal SaaS"),
    ("ppcassist.com", "PPC Assist", "TinySeed", "PPC/ad management SaaS"),
    ("rootabl.com", "Rootabl", "TinySeed", "SaaS platform"),
    ("getsombra.com", "Sombra", "TinySeed", "Developer tools SaaS"),
    ("getspindle.com", "Spindle", "TinySeed", "Project management SaaS"),
    ("checkoutpage.co", "CheckoutPage", "TinySeed", "Checkout SaaS"),
    ("marllm.io", "Mar LLM", "TinySeed", "AI/LLM SaaS"),
    ("wanotifier.com", "WA Notifier", "TinySeed", "WhatsApp notification SaaS"),
    ("vendorsage.com", "VendorSage", "TinySeed", "Vendor management SaaS"),
    ("myteamfluence.com", "MyTeamFluence", "TinySeed", "Team analytics SaaS"),
    ("sitio.ai", "Sitio AI", "TinySeed", "AI SaaS"),
    ("scalelist.com", "ScaleList", "TinySeed", "Email outreach SaaS"),
    ("leadcapture.io", "Lead Capture", "TinySeed", "Lead capture SaaS"),
    ("kennellink.com", "KennelLink", "TinySeed", "Pet business SaaS"),
    ("getdrum.com", "Drum", "TinySeed", "Freelance SaaS"),
    ("blinkmetrics.com", "Blink Metrics", "TinySeed", "Analytics SaaS"),
    ("rentkit.com", "RentKit", "TinySeed", "Rental management SaaS"),
    ("avohq.io", "Avo", "TinySeed", "Product analytics SaaS"),
    ("growform.co", "Growform", "TinySeed", "Multi-step form SaaS"),
    ("linklo.io", "Linklo", "TinySeed", "LinkedIn automation SaaS"),
    ("marcode.ai", "Marcode AI", "TinySeed", "AI SaaS"),
    ("reviewflowz.com", "ReviewFlowz", "TinySeed", "Review management SaaS"),
    ("userdoc.fyi", "UserDoc", "TinySeed", "User documentation SaaS"),
    ("trot.to", "Trot", "TinySeed", "Team events SaaS"),
    ("tooltribe.com", "ToolTribe", "TinySeed", "Tools marketplace"),
    ("outboundsync.com", "OutboundSync", "TinySeed", "Sales sync SaaS"),
    ("nekst.com", "Nekst", "TinySeed", "Real estate SaaS"),
    ("joinmoov.com", "Moov", "TinySeed", "Finance SaaS"),
    ("gentext.ai", "GenText AI", "TinySeed", "AI content SaaS"),
    ("wrenly.ai", "Wrenly AI", "TinySeed", "AI writing SaaS"),
    ("upsheets.com", "UpSheets", "TinySeed", "Spreadsheet SaaS"),
    ("trainermetrics.com", "Trainer Metrics", "TinySeed", "Fitness business SaaS"),
    ("shrpa.com", "Shrpa", "TinySeed", "Influencer marketing SaaS"),
    ("rewardup.com", "RewardUp", "TinySeed", "Loyalty/rewards SaaS"),
    ("relayhawk.com", "RelayHawk", "TinySeed", "Communication SaaS"),
    ("dealintent.com", "DealIntent", "TinySeed", "Sales intent SaaS"),
    ("mawi.io", "Mawi", "TinySeed", "Analytics SaaS"),
    ("refactoros.com", "Refactor OS", "TinySeed", "Dev tools SaaS"),
    ("adaptify.ai", "Adaptify AI", "TinySeed", "AI SEO SaaS"),
    ("classcardapp.com", "ClassCard", "TinySeed", "Class scheduling SaaS"),
    ("cliezen.com", "Cliezen", "TinySeed", "Client management SaaS"),
    ("mybridalsoftware.com", "My Bridal Software", "TinySeed", "Wedding industry SaaS"),
    ("myplace.app", "MyPlace", "TinySeed", "Hospitality SaaS"),
    ("txtsquad.com", "TxtSquad", "TinySeed", "SMS marketing SaaS"),
    ("legal27.com", "Legal27", "TinySeed", "Legal SaaS"),
    ("hivrs.com", "Hivrs", "TinySeed", "Operations SaaS"),
    ("gandaya.io", "Gandaya", "TinySeed", "Event ticketing SaaS"),
    ("foliume.com", "Foliume", "TinySeed", "Portfolio SaaS"),
    ("detamoov.com", "Detamoov", "TinySeed", "Auto detailing SaaS"),
    ("datacoves.com", "DataCoves", "TinySeed", "Data engineering SaaS"),
    ("castmetrics.ai", "Cast Metrics AI", "TinySeed", "Advertising analytics SaaS"),
    ("andsuper.com", "AndSuper", "TinySeed", "HR SaaS"),
    ("siterecon.ai", "SiteRecon AI", "TinySeed", "Site intelligence SaaS"),
    ("sessionlab.com", "SessionLab", "TinySeed", "Workshop planning SaaS"),
    ("panoramata.co", "Panoramata", "TinySeed", "Marketing monitoring SaaS"),
    ("mycustomerlens.com", "My Customer Lens", "TinySeed", "Customer research SaaS"),
    ("heysummit.com", "HeySummit", "TinySeed", "Virtual summit SaaS"),
    ("handicaddie.com", "HandiCaddie", "TinySeed", "Golf app SaaS"),
    ("verificationmanager.com", "Verification Manager", "TinySeed", "Identity verification SaaS"),
    ("nextchannel.com", "NextChannel", "TinySeed", "Channel partner SaaS"),
    ("statusgator.com", "StatusGator", "TinySeed", "Status monitoring SaaS"),
    ("savio.io", "Savio", "TinySeed", "Customer feedback SaaS"),
    ("postpone.app", "Postpone", "TinySeed", "Reddit scheduling SaaS"),
    ("hammerstone.dev", "Hammerstone", "TinySeed", "Query builder SaaS"),
    ("glitchsecure.com", "GlitchSecure", "TinySeed", "Security testing SaaS"),
    ("currents.dev", "Currents Dev", "TinySeed", "Cypress test analytics SaaS"),
    ("beyondware.com", "Beyondware", "TinySeed", "Software SaaS"),
    ("anchorpoint.app", "Anchorpoint", "TinySeed", "Version control SaaS"),
    ("stridist.com", "Stridist", "TinySeed", "Coaching SaaS"),
    ("plainlyvideos.com", "Plainly Videos", "TinySeed", "Video automation SaaS"),
    ("frontendmentor.io", "Frontend Mentor", "TinySeed", "Developer practice platform"),
    ("findymail.com", "Findymail", "TinySeed", "Email finder SaaS"),
    ("desku.io", "Desku", "TinySeed", "Customer support SaaS"),
    ("audiencetap.com", "AudienceTap", "TinySeed", "Audience analytics SaaS"),
    ("spraye.io", "Spraye", "TinySeed", "Landscaping SaaS"),
    ("noterouter.com", "Note Router", "TinySeed", "Note management SaaS"),
    ("knackly.io", "Knackly", "TinySeed", "Document automation SaaS"),
    ("jamyr.com", "Jamyr", "TinySeed", "Video testimonial SaaS"),
    ("docsales.com", "DocSales", "TinySeed", "Document sales SaaS"),
    ("cobaltintelligence.com", "Cobalt Intelligence", "TinySeed", "Data intelligence SaaS"),
    ("getbommer.com", "Bommer", "TinySeed", "BIM SaaS"),
    ("byautomata.io", "Automata", "TinySeed", "Content research SaaS"),
    ("whaleblue.app", "Whale Blue", "TinySeed", "SaaS metrics"),
    ("seotesting.com", "SEO Testing", "TinySeed", "SEO testing SaaS"),
    ("jboard.io", "JBoard", "TinySeed", "Job board SaaS"),
    ("senturo.com", "Senturo", "TinySeed", "Device tracking SaaS"),
    ("debugbear.com", "DebugBear", "TinySeed", "Web performance SaaS"),
    ("consentkit.com", "ConsentKit", "TinySeed", "Cookie consent SaaS"),
    ("waylit.com", "WayLit", "TinySeed", "Wayfinding SaaS"),
    ("trendful.com", "Trendful", "TinySeed", "Trend intelligence SaaS"),
    ("skysnag.com", "Skysnag", "TinySeed", "Email security SaaS"),
    ("panelfox.io", "PanelFox", "TinySeed", "Research panel SaaS"),
    ("nestify.io", "Nestify", "TinySeed", "Hosting SaaS"),
    ("keeping.com", "Keeping", "TinySeed", "Help desk SaaS"),
    ("clienthub.app", "ClientHub", "TinySeed", "Client management SaaS"),
    ("churnkey.co", "Churnkey", "TinySeed", "Churn reduction SaaS"),
    ("activitymessenger.com", "Activity Messenger", "TinySeed", "Activity management SaaS"),
    ("gymdesk.com", "GymDesk", "TinySeed", "Gym management SaaS"),
    ("callscaler.com", "CallScaler", "TinySeed", "Call tracking SaaS"),
    ("kioskbuddy.app", "KioskBuddy", "TinySeed", "Kiosk SaaS"),
    ("zentake.com", "ZenTake", "TinySeed", "Intake form SaaS"),
    ("testable.org", "Testable", "TinySeed", "Research SaaS"),
    ("securitystudio.com", "Security Studio", "TinySeed", "Cybersecurity SaaS"),
    ("postaga.com", "Postaga", "TinySeed", "Outreach SaaS"),
    ("planifi.net", "Planifi", "TinySeed", "Project planning SaaS"),
    ("newscatcherapi.com", "NewsCatcher API", "TinySeed", "News API SaaS"),
    ("mspcfo.com", "MSPCFO", "TinySeed", "MSP financial SaaS"),
    ("localyser.com", "Localyser", "TinySeed", "Local SEO SaaS"),
    ("getlasso.co", "Lasso", "TinySeed", "Affiliate marketing SaaS"),
    ("harborplan.com", "HarborPlan", "TinySeed", "Marina management SaaS"),
    ("craftybase.com", "Craftybase", "TinySeed", "Craft business SaaS"),
    ("cloudforecast.io", "CloudForecast", "TinySeed", "Cloud cost SaaS"),
    ("breachsense.io", "BreachSense", "TinySeed", "Breach monitoring SaaS"),
    ("aureliuslab.com", "Aurelius Lab", "TinySeed", "User research SaaS"),
    ("brandchamp.io", "BrandChamp", "TinySeed", "Brand ambassador SaaS"),
    ("userlist.io", "Userlist", "TinySeed", "Email automation SaaS"),
    ("squadcast.fm", "Squadcast", "TinySeed", "Podcast recording SaaS"),
    ("segmetrics.io", "SegMetrics", "TinySeed", "Marketing attribution SaaS"),
    ("seekwell.io", "SeekWell", "TinySeed", "SQL reporting SaaS"),
    ("scrapingbee.com", "ScrapingBee", "TinySeed", "Web scraping SaaS"),
    ("scoutdns.com", "ScoutDNS", "TinySeed", "DNS filtering SaaS"),
    ("reftab.com", "Reftab", "TinySeed", "Asset tracking SaaS"),
    ("dealforma.com", "DealForma", "TinySeed", "M&A SaaS"),
    ("codesubmit.io", "CodeSubmit", "TinySeed", "Technical assessment SaaS"),
    ("builderprime.com", "BuilderPrime", "TinySeed", "Contractor CRM SaaS"),
    ("bluerithm.com", "Bluerithm", "TinySeed", "Construction quality SaaS"),
    ("signwell.com", "SignWell", "TinySeed", "E-signature SaaS"),
    ("savvycal.com", "SavvyCal", "TinySeed", "Scheduling SaaS"),
    ("usesummit.com", "Summit", "TinySeed", "Customer onboarding SaaS"),
    ("getpopsicle.com", "Popsicle", "TinySeed", "SaaS"),
    ("reimbi.com", "Reimbi", "TinySeed", "Expense reimbursement SaaS"),
    ("loadster.app", "Loadster", "TinySeed", "Load testing SaaS"),
    ("lessaccounting.com", "Less Accounting", "TinySeed", "Accounting SaaS"),
    ("gatherit.co", "GatherIt", "TinySeed", "Data collection SaaS"),
    ("clientrock.com", "ClientRock", "TinySeed", "Client portal SaaS"),
    ("castos.com", "Castos", "TinySeed", "Podcast hosting SaaS"),
    ("reform.app", "Reform", "TinySeed", "Form builder SaaS"),

    # ========== Calm Company Fund (Earnest Capital) Portfolio ==========
    ("uplisting.io", "Uplisting", "CalmFund", "Short-term rental management SaaS"),
    ("economize.cloud", "Economize", "CalmFund", "Cloud cost optimization SaaS"),
    ("pulse360.com", "Pulse360", "CalmFund", "Financial advisor meeting SaaS"),
    ("pitchgauge.com", "Pitch Gauge", "CalmFund", "Roofing CRM SaaS"),
    ("alitu.com", "Alitu", "CalmFund", "Podcast publishing SaaS"),
    ("datasketch.io", "Datasketch", "CalmFund", "Data science tools SaaS"),
    ("featured.com", "Featured", "CalmFund", "Expert quote platform"),
    ("soldlive.com", "SoldLive", "CalmFund", "Livestream shopping SaaS"),
    ("sparkloop.com", "SparkLoop", "CalmFund", "Newsletter referral SaaS"),
    ("refiner.io", "Refiner", "CalmFund", "User research SaaS"),
    ("enjoyhq.com", "EnjoyHQ", "CalmFund", "User research repository SaaS"),
    ("contentharmony.com", "Content Harmony", "CalmFund", "Content marketing SaaS"),
    ("detangle.ai", "Detangle", "CalmFund", "Legal document SaaS"),
    ("pushpress.com", "PushPress", "CalmFund", "Gym management SaaS"),
    ("nativshark.com", "NativShark", "CalmFund", "Japanese learning SaaS"),
    ("conversioncrimes.com", "Conversion Crimes", "CalmFund", "UX testing SaaS"),
    ("clarityflow.com", "ClarityFlow", "CalmFund", "Coaching platform SaaS"),
    ("citygrows.com", "CityGrows", "CalmFund", "Government workflow SaaS"),
    ("responsevault.com", "ResponseVault", "CalmFund", "Construction inspection SaaS"),
    ("hoalife.io", "HOALife", "CalmFund", "HOA management SaaS"),
    ("scripto.live", "Scripto", "CalmFund", "Collaborative scriptwriting SaaS"),
    ("hostifi.com", "HostiFi", "CalmFund", "Ubiquiti cloud hosting SaaS"),
    ("firstbase.io", "FirstBase", "CalmFund", "US company formation SaaS"),
    ("backtrack.team", "Backtrack", "CalmFund", "Meeting recorder SaaS"),
    ("manyrequests.com", "ManyRequests", "CalmFund", "Client portal SaaS"),
    ("cachix.org", "Cachix", "CalmFund", "Nix binary cache SaaS"),
    ("every.to", "Every", "CalmFund", "Newsletter bundle SaaS"),
    ("jetboost.io", "Jetboost", "CalmFund", "Webflow add-ons SaaS"),
    ("1se.co", "1 Second Everyday", "CalmFund", "Video memory app"),
    ("endcrawl.com", "Endcrawl", "CalmFund", "Film credits SaaS"),
    ("docspring.com", "DocSpring", "CalmFund", "PDF generation API SaaS"),
    ("makerpad.co", "Makerpad", "CalmFund", "No-code education SaaS"),
    ("typefully.com", "Typefully", "CalmFund", "Twitter content SaaS"),
    ("callingly.com", "Callingly", "CalmFund", "Lead response SaaS"),
    ("foodready.ai", "FoodReady.ai", "CalmFund", "Food safety SaaS"),
    ("rotabull.com", "Rotabull", "CalmFund", "Aircraft parts marketplace"),
    ("testimonial.to", "Testimonial", "CalmFund", "Video testimonial SaaS"),
    ("tally.so", "Tally", "CalmFund", "Form builder SaaS"),
    ("analyzify.com", "Analyzify", "CalmFund", "Shopify analytics SaaS"),
    ("instatus.com", "Instatus", "CalmFund", "Status page SaaS"),
    ("memberspace.com", "MemberSpace", "CalmFund", "Membership SaaS"),
    ("junglebee.com", "Junglebee", "CalmFund", "Booking SaaS"),

    # ========== YC W24 Batch ==========
    ("parcelbio.com", "Parcel Bio", "YC-W24", "Biotech SaaS"),
    ("kscale.dev", "K-Scale Labs", "YC-W24", "Robotics AI"),
    ("marrlabs.com", "Marr Labs", "YC-W24", "Voice AI SaaS"),
    ("dropback.com", "Dropback", "YC-W24", "Sports tech SaaS"),
    ("retailreadyai.com", "RetailReady", "YC-W24", "Retail AI SaaS"),
    ("million.dev", "Million Software", "YC-W24", "React optimization SaaS"),
    ("nowhouse.io", "NowHouse", "YC-W24", "Real estate SaaS"),
    ("getcrux.ai", "GetCrux", "YC-W24", "Analytics AI SaaS"),
    ("repromptai.com", "Reprompt", "YC-W24", "AI testing SaaS"),
    ("inspectmind.ai", "InspectMind", "YC-W24", "Inspection AI SaaS"),
    ("yarn.so", "Yarn", "YC-W24", "Content SaaS"),
    ("blacksmith.sh", "Blacksmith", "YC-W24", "CI/CD SaaS"),
    ("crowdvolt.com", "CrowdVolt", "YC-W24", "Events SaaS"),
    ("kater.ai", "Kater", "YC-W24", "Data analytics SaaS"),
    ("withtower.com", "Tower", "YC-W24", "Construction management SaaS"),
    ("quivr.app", "Quivr", "YC-W24", "AI knowledge base SaaS"),
    ("dragoneye.ai", "Dragoneye", "YC-W24", "Vision AI SaaS"),
    ("renderlet.com", "Renderlet", "YC-W24", "WASM rendering SaaS"),
    ("fumedev.com", "Fume Technologies", "YC-W24", "Dev automation SaaS"),
    ("integuru.ai", "Integuru", "YC-W24", "Integration SaaS"),
    ("konstructly.com", "Konstructly", "YC-W24", "Construction SaaS"),
    ("marblism.com", "Marblism", "YC-W24", "Full-stack SaaS builder"),
    ("commodityai.io", "Commodity AI", "YC-W24", "Commodity management SaaS"),
    ("getveles.com", "Veles", "YC-W24", "Construction measurement SaaS"),
    ("miden.co", "Miden", "YC-W24", "African fintech SaaS"),
    ("getfluently.app", "Fluently", "YC-W24", "Language learning SaaS"),
    ("basepilot.com", "Basepilot", "YC-W24", "Workflow automation SaaS"),
    ("withaqua.com", "Aqua Voice", "YC-W24", "Voice dictation SaaS"),
    ("xpaycheckout.com", "xPay", "YC-W24", "Payment SaaS"),
    ("deepnight.ai", "Deepnight", "YC-W24", "Defense AI SaaS"),
    ("vistapower.com", "Vista Power", "YC-W24", "Energy SaaS"),
    ("useocular.com", "Ocular", "YC-W24", "Engineering analytics SaaS"),
    ("retellai.com", "Retell AI", "YC-W24", "Voice AI SaaS"),
    ("rovecard.com", "Rove Card", "YC-W24", "Travel rewards SaaS"),
    ("camelai.com", "CamelAI", "YC-W24", "Data analytics AI SaaS"),
    ("downlink.dev", "Downlink", "YC-W24", "Menu bar app SaaS"),
    ("terrakotta.ai", "Terrakotta", "YC-W24", "Voicemail AI SaaS"),
    ("stacksync.cloud", "Stacksync", "YC-W24", "Real-time sync SaaS"),
    ("hatchet.run", "Hatchet", "YC-W24", "Background job SaaS"),
    ("shepherd.study", "Shepherd", "YC-W24", "EdTech SaaS"),
    ("sonauto.ai", "Sonauto", "YC-W24", "AI music generation SaaS"),
    ("getzep.com", "Zep", "YC-W24", "AI memory layer SaaS"),
    ("openmart.com", "Openmart", "YC-W24", "Retail discovery SaaS"),
    ("thorntale.com", "Thorntale", "YC-W24", "Digital cards SaaS"),
    ("getalai.com", "Alai", "YC-W24", "AI automation SaaS"),
    ("pocketpod.app", "Pocket AI", "YC-W24", "AI companion app"),
    ("samplehc.com", "Sample Healthcare", "YC-W24", "Healthcare SaaS"),
    ("usebrainbase.com", "Brainbase", "YC-W24", "Workflow automation SaaS"),
    ("focalml.com", "Focal", "YC-W24", "ML analytics SaaS"),
    ("givefront.com", "Givefront", "YC-W24", "Donor-advised fund SaaS"),
    ("getcleva.com", "Cleva", "YC-W24", "African banking SaaS"),

    # ========== YC S24 Batch ==========
    ("outerport.com", "Outerport", "YC-S24", "Portability SaaS"),
    ("dreamrp.com", "DreamRP", "YC-S24", "Roleplay AI SaaS"),
    ("melty.sh", "Melty", "YC-S24", "AI code editor"),
    ("getpathpilot.com", "PathPilot", "YC-S24", "Routing SaaS"),
    ("standarddata.com", "Standard Data", "YC-S24", "Data standardization SaaS"),
    ("trykairo.com", "Kairo Health", "YC-S24", "Health SaaS"),
    ("midship.ai", "Midship", "YC-S24", "AI SaaS"),
    ("simcare.ai", "SimCare AI", "YC-S24", "Medical simulation SaaS"),
    ("arva.ai", "Arva AI", "YC-S24", "Compliance AI SaaS"),
    ("affil.ai", "Affil.ai", "YC-S24", "Affiliate AI SaaS"),
    ("orgorg.com", "OrgOrg", "YC-S24", "Org management SaaS"),
    ("patched.codes", "Patched Codes", "YC-S24", "Dev automation SaaS"),
    ("usemica.com", "Mica", "YC-S24", "Real estate SaaS"),
    ("formulainsight.io", "Formula Insight", "YC-S24", "F1 analytics SaaS"),
    ("joinoverlap.com", "Overlap", "YC-S24", "Community SaaS"),
    ("capitol.ai", "Capitol AI", "YC-S24", "Policy AI SaaS"),
    ("generalanalysis.com", "General Analysis", "YC-S24", "AI analysis SaaS"),
    ("voideditor.com", "Glass Devtools", "YC-S24", "AI code editor"),
    ("anglera.com", "Anglera", "YC-S24", "Insurance SaaS"),
    ("felafax.ai", "Felafax", "YC-S24", "LLM fine-tuning SaaS"),
    ("henry.ai", "Henry AI", "YC-S24", "Construction SaaS"),
    ("heyrevia.ai", "Revia", "YC-S24", "AI SaaS"),
    ("ficra.ai", "Ficra", "YC-S24", "Financial AI SaaS"),
    ("rowboatlabs.com", "RowBoat Labs", "YC-S24", "AI agent SaaS"),
    ("pipeshift.com", "Pipeshift", "YC-S24", "ML ops SaaS"),
    ("pharos.health", "Pharos", "YC-S24", "Healthcare SaaS"),
    ("trykeet.com", "Keet", "YC-S24", "Mobility SaaS"),
    ("useterra.com", "Terra", "YC-S24", "Furniture SaaS"),
    ("aisell.tech", "aiSell", "YC-S24", "AI sales SaaS"),
    ("surebright.com", "SureBright", "YC-S24", "Insurance SaaS"),
    ("usul.com", "Usul", "YC-S24", "Policy management SaaS"),
    ("saldor.com", "Saldor", "YC-S24", "Payments SaaS"),
    ("bucket.bot", "Bucket Robotics", "YC-S24", "Robotics SaaS"),
    ("elayne.com", "Elayne", "YC-S24", "Estate management SaaS"),
    ("blaze.money", "Blaze Payments", "YC-S24", "Fintech SaaS"),
    ("joinpap.com", "PAP", "YC-S24", "Social SaaS"),
    ("therentflow.com", "RentFlow", "YC-S24", "Rental payment SaaS"),
    ("tradeflowai.com", "TradeFlow", "YC-S24", "Trade finance SaaS"),
    ("voker.ai", "Voker", "YC-S24", "Voice AI SaaS"),
    ("getquetzal.com", "Quetzal Labs", "YC-S24", "Supply chain SaaS"),
    ("typa.ai", "Weavel/Typa", "YC-S24", "Product analytics SaaS"),
    ("moretapay.com", "Moreta", "YC-S24", "Payments SaaS"),
    ("focusbuddy.ai", "Focus Buddy", "YC-S24", "Productivity SaaS"),
    ("simplifine.com", "Simplifine", "YC-S24", "LLM fine-tuning SaaS"),
    ("sepalai.com", "Sepal AI", "YC-S24", "AI SaaS"),
    ("assemblyhoa.com", "Assembly HOA", "YC-S24", "HOA management SaaS"),
    ("omnidock.com", "Omnidock", "YC-S24", "Multichannel commerce SaaS"),
    ("polymet.ai", "Polymet", "YC-S24", "UI generation SaaS"),
    ("getremo.ai", "Remo", "YC-S24", "Reimbursement SaaS"),
    ("propaya.com", "Propaya", "YC-S24", "Property SaaS"),
    ("argil.ai", "Argil", "YC-S24", "AI avatar SaaS"),
    ("zeropath.com", "ZeroPath", "YC-S24", "Security SaaS"),
    ("starcloud.com", "Starcloud", "YC-S24", "GPU cloud SaaS"),
    ("dataleap.ai", "Dataleap", "YC-S24", "Data analytics SaaS"),
    ("withzimi.com", "Zimi", "YC-S24", "Business services SaaS"),
    ("meetthyme.com", "Thyme", "YC-S24", "Scheduling SaaS"),
    ("ionworks.com", "Ionworks", "YC-S24", "Battery simulation SaaS"),
    ("rescript.ai", "Rescript", "YC-S24", "Multilingual AI SaaS"),
    ("heroui.com", "HeroUI", "YC-S24", "UI components SaaS"),
    ("tryhelium.com", "Helium", "YC-S24", "eSIM SaaS"),
    ("tryandai.com", "AndAI", "YC-S24", "Patent AI SaaS"),
    ("haystackeditor.com", "Haystack Editor", "YC-S24", "Code editor SaaS"),
    ("finosu.com", "Finosu", "YC-S24", "Financial SaaS"),
    ("odo.do", "Odo Labs", "YC-S24", "Supply chain SaaS"),
    ("baselinetrials.com", "Baseline Trials", "YC-S24", "Clinical trial SaaS"),
    ("riskangle.com", "RiskAngle", "YC-S24", "Risk management SaaS"),
    ("winfordwealth.com", "Winford Wealth", "YC-S24", "Wealth management SaaS"),
    ("cartage.ai", "Cartage AI", "YC-S24", "Trucking SaaS"),
    ("paasa.com", "Paasa", "YC-S24", "Payments SaaS"),
    ("withblast.com", "Blast Labs", "YC-S24", "Loyalty SaaS"),

    # ========== State Startup Lists ==========
    ("ninjaone.com", "NinjaOne", "TX-StartupList", "IT management SaaS"),
    ("inkind.com", "inKind", "TX-StartupList", "Restaurant funding SaaS"),
    ("kickfin.com", "Kickfin", "TX-StartupList", "Tip management SaaS"),
    ("jobtread.com", "JobTread", "TX-StartupList", "Construction management SaaS"),
    ("highlevel.com", "HighLevel", "TX-StartupList", "Marketing agency SaaS"),
    ("aiwyn.com", "Aiwyn", "NC-StartupList", "Accounting firm SaaS"),
    ("spreedly.com", "Spreedly", "NC-StartupList", "Payment orchestration SaaS"),
    ("apiture.com", "Apiture", "NC-StartupList", "Digital banking SaaS"),
    ("pendo.io", "Pendo", "NC-StartupList", "Product analytics SaaS"),
    ("stord.com", "Stord", "GA-StartupList", "Commerce enablement SaaS"),
    ("sheerid.com", "SheerID", "OR-StartupList", "Identity verification SaaS"),
    ("exterro.com", "Exterro", "OR-StartupList", "Legal SaaS"),
    ("hydrolix.io", "Hydrolix", "OR-StartupList", "Data lake SaaS"),
    ("champtitles.com", "CHAMP Titles", "OH-StartupList", "Vehicle title SaaS"),
    ("keyfactor.com", "Keyfactor", "OH-StartupList", "PKI/identity SaaS"),
    ("tradingview.com", "TradingView", "OH-StartupList", "Trading analytics SaaS"),
    ("debtbook.com", "DebtBook", "NC-StartupList", "Public finance SaaS"),
    ("logicmonitor.com", "LogicMonitor", "NC-StartupList", "IT monitoring SaaS"),
    ("simporter.com", "Simporter", "GA-StartupList", "Predictive analytics SaaS"),
    ("flock.com", "Flock Safety", "GA-StartupList", "Public safety SaaS"),

    # ========== MicroConf Ecosystem ==========
    ("sparktoro.com", "SparkToro", "MicroConf", "Audience research SaaS"),
    ("demandmaven.io", "Demand Maven", "MicroConf", "SaaS growth consulting"),
    ("tinyseed.com", "TinySeed", "MicroConf", "Bootstrapped startup accelerator"),
    ("webinarninja.com", "WebinarNinja", "MicroConf", "Webinar hosting SaaS"),
    ("balsamiq.com", "Balsamiq", "MicroConf", "Wireframing SaaS"),
    ("procurementexpress.com", "ProcurementExpress", "MicroConf", "Purchase order SaaS"),

    # ========== Additional US SaaS Companies ==========
    ("rankbreeze.com", "RankBreeze", "DirectoryMining", "Amazon SEO SaaS"),
    ("civicreview.com", "CivicReview", "DirectoryMining", "Government review SaaS"),
    ("monolithforensics.com", "Monolith Forensics", "DirectoryMining", "Digital forensics SaaS"),
    ("scatterspoke.com", "ScatterSpoke", "DirectoryMining", "Team retrospectives SaaS"),
    ("railsautoscale.com", "RailsAutoscale", "DirectoryMining", "Rails hosting SaaS"),
    ("mspcfo.com", "MSPCFO", "DirectoryMining", "MSP financial SaaS"),
    ("builderprime.com", "BuilderPrime", "DirectoryMining", "Contractor CRM SaaS"),
    ("codesubmit.io", "CodeSubmit", "DirectoryMining", "Technical hiring SaaS"),
    ("signwell.com", "SignWell", "DirectoryMining", "E-signature SaaS"),
    ("seekwell.io", "SeekWell", "DirectoryMining", "SQL-to-sheets SaaS"),
    ("scrapingbee.com", "ScrapingBee", "DirectoryMining", "Web scraping SaaS"),
    ("dealforma.com", "Dealforma", "DirectoryMining", "Deal tracking SaaS"),
    ("glitchsecure.com", "GlitchSecure", "DirectoryMining", "Security SaaS"),
    ("breachsense.io", "BreachSense", "DirectoryMining", "Data breach SaaS"),
    ("statusgator.com", "StatusGator", "DirectoryMining", "Status monitoring SaaS"),
    ("savio.io", "Savio", "DirectoryMining", "Feature voting SaaS"),
    ("userlist.io", "Userlist", "DirectoryMining", "Email for SaaS"),
    ("lessaccounting.com", "Less Accounting", "DirectoryMining", "Small biz accounting SaaS"),
    ("craftybase.com", "Craftybase", "DirectoryMining", "Maker biz SaaS"),
    ("cloudforecast.io", "CloudForecast", "DirectoryMining", "Cloud cost SaaS"),
    ("reftab.com", "Reftab", "DirectoryMining", "Asset tracking SaaS"),
    ("hammerstone.dev", "Hammerstone", "DirectoryMining", "Laravel query SaaS"),
    ("debugbear.com", "DebugBear", "DirectoryMining", "Performance monitoring SaaS"),
    ("panelfox.io", "PanelFox", "DirectoryMining", "Research recruitment SaaS"),
    ("aureliuslab.com", "Aurelius Lab", "DirectoryMining", "User research SaaS"),
    ("brandchamp.io", "BrandChamp", "DirectoryMining", "Ambassador program SaaS"),
    ("segmetrics.io", "SegMetrics", "DirectoryMining", "Marketing analytics SaaS"),
    ("squadcast.fm", "Squadcast", "DirectoryMining", "Podcast production SaaS"),
    ("castos.com", "Castos", "DirectoryMining", "Podcast hosting SaaS"),
    ("gymdesk.com", "GymDesk", "DirectoryMining", "Gym management SaaS"),
    ("churnkey.co", "Churnkey", "DirectoryMining", "Churn prevention SaaS"),
    ("keeping.com", "Keeping", "DirectoryMining", "Gmail help desk SaaS"),
    ("clienthub.app", "ClientHub", "DirectoryMining", "Freelancer client mgmt SaaS"),
    ("reform.app", "Reform", "DirectoryMining", "Form building SaaS"),
    ("savvycal.com", "SavvyCal", "DirectoryMining", "Scheduling SaaS"),
    ("signwell.com", "SignWell", "DirectoryMining", "E-sign SaaS"),
    ("userlist.io", "Userlist", "DirectoryMining", "Email automation SaaS"),
    ("sessionlab.com", "SessionLab", "DirectoryMining", "Workshop planning SaaS"),
    ("panoramata.co", "Panoramata", "DirectoryMining", "Marketing spy SaaS"),
    ("newscatcherapi.com", "NewsCatcher API", "DirectoryMining", "News API"),
    ("desku.io", "Desku", "DirectoryMining", "Customer support SaaS"),
    ("postaga.com", "Postaga", "DirectoryMining", "Link building SaaS"),
    ("findymail.com", "Findymail", "DirectoryMining", "Email finder SaaS"),
    ("frontendmentor.io", "Frontend Mentor", "DirectoryMining", "Dev learning platform"),
    ("plainlyvideos.com", "Plainly Videos", "DirectoryMining", "Video automation SaaS"),
    ("stridist.com", "Stridist", "DirectoryMining", "Coaching business SaaS"),
    ("testable.org", "Testable", "DirectoryMining", "Research platform SaaS"),
    ("bluerithm.com", "Bluerithm", "DirectoryMining", "Construction quality SaaS"),
    ("loadster.app", "Loadster", "DirectoryMining", "Load testing SaaS"),
    ("postpone.app", "Postpone", "DirectoryMining", "Reddit scheduler SaaS"),
    ("seotesting.com", "SEO Testing", "DirectoryMining", "SEO experiment SaaS"),
    ("senturo.com", "Senturo", "DirectoryMining", "Device tracking SaaS"),
    ("nestify.io", "Nestify", "DirectoryMining", "Hosting management SaaS"),
    ("consentkit.com", "ConsentKit", "DirectoryMining", "Privacy consent SaaS"),
    ("kioskbuddy.app", "KioskBuddy", "DirectoryMining", "Kiosk checkout SaaS"),
    ("zentake.com", "ZenTake", "DirectoryMining", "Digital intake SaaS"),
    ("activitymessenger.com", "Activity Messenger", "DirectoryMining", "Rec program SaaS"),
    ("callscaler.com", "CallScaler", "DirectoryMining", "Call tracking SaaS"),
    ("anchorpoint.app", "Anchorpoint", "DirectoryMining", "Git version control SaaS"),
    ("skysnag.com", "Skysnag", "DirectoryMining", "Email auth SaaS"),
    ("trendful.com", "Trendful", "DirectoryMining", "Market trends SaaS"),
    ("waylit.com", "WayLit", "DirectoryMining", "Learning SaaS"),
    ("knackly.io", "Knackly", "DirectoryMining", "Document assembly SaaS"),
    ("jamyr.com", "Jamyr", "DirectoryMining", "Video content SaaS"),
    ("getbommer.com", "Bommer", "DirectoryMining", "BIM export SaaS"),
    ("byautomata.io", "Automata", "DirectoryMining", "Content intelligence SaaS"),
    ("cobaltintelligence.com", "Cobalt Intelligence", "DirectoryMining", "Business data SaaS"),
    ("docsales.com", "DocSales", "DirectoryMining", "e-Signature/sales SaaS"),
    ("harborplan.com", "HarborPlan", "DirectoryMining", "Marina management SaaS"),
    ("getlasso.co", "Lasso", "DirectoryMining", "Affiliate link mgmt SaaS"),
    ("gatherit.co", "GatherIt", "DirectoryMining", "Data collection SaaS"),
    ("clientrock.com", "ClientRock", "DirectoryMining", "Client scheduling SaaS"),
    ("audiencetap.com", "AudienceTap", "DirectoryMining", "Email/SMS SaaS"),
    ("spraye.io", "Spraye", "DirectoryMining", "Landscape business SaaS"),
    ("noterouter.com", "Note Router", "DirectoryMining", "Notes to email SaaS"),

]

# Dedup and filter
ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
new_entries = []
seen_in_batch = set()

for domain, name, source, desc in RAW_COMPANIES:
    domain = domain.lower().strip()
    if not domain:
        continue
    if domain in existing:
        continue
    if domain in seen_in_batch:
        continue
    seen_in_batch.add(domain)
    entry = {
        "domain": domain,
        "company_name": name,
        "source": source,
        "employees": None,
        "state": None,
        "description": desc,
        "timestamp": ts
    }
    new_entries.append(entry)

print(f"New unique entries to add: {len(new_entries)}")

# Append to queue
with open(QUEUE, 'a') as f:
    for entry in new_entries:
        f.write(json.dumps(entry) + '\n')

print("Done!")
print(f"Sample new domains:")
for e in new_entries[:10]:
    print(f"  {e['domain']} - {e['company_name']}")
