#!/usr/bin/env python3
"""
Session 1 Batch 2: More companies from additional sources.
"""

import json
import sqlite3
import os
import re
from datetime import datetime, timezone

WORKSPACE = "/Users/corgi12/.eragon-joshua_augustine/joshua_augustine_workspace"
HUBSPOT_DOMAINS_PATH = f"{WORKSPACE}/jordan.ai/overnight/shared/hubspot_domains_current.json"
MASTER_DB_PATH = f"{WORKSPACE}/jordan.ai/pipeline/master.db"
QUEUE_PATH = f"{WORKSPACE}/jordan.ai/overnight/shared/new_companies_queue.jsonl"

print("Loading existing domains...")
with open(HUBSPOT_DOMAINS_PATH) as f:
    hubspot_domains = set(json.load(f))

conn = sqlite3.connect(MASTER_DB_PATH)
cursor = conn.cursor()
cursor.execute("SELECT domain FROM companies WHERE domain IS NOT NULL")
db_domains = set(row[0].lower().strip() for row in cursor.fetchall())
conn.close()

# Also load already-queued domains from this run
queued_domains = set()
try:
    with open(QUEUE_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    e = json.loads(line)
                    queued_domains.add(e.get("domain", "").lower())
                except:
                    pass
except FileNotFoundError:
    pass

all_existing = hubspot_domains | db_domains | queued_domains
print(f"  Total existing + queued: {len(all_existing):,} domains")


def is_new(domain):
    d = domain.lower().strip()
    return d not in all_existing and d != "" and "." in d


def normalize_domain(url):
    if not url:
        return None
    url = url.strip()
    url = re.sub(r'^https?://', '', url)
    url = re.sub(r'^www\.', '', url)
    url = url.split('/')[0]
    url = url.split(':')[0]
    url = url.split('?')[0]
    url = url.strip().lower()
    if url and '.' in url and len(url) > 3:
        return url
    return None


def append_to_queue(entries):
    with open(QUEUE_PATH, 'a') as f:
        for e in entries:
            f.write(json.dumps(e) + "\n")


# ========================
# SOURCE: ROSS Index 2024 (TechCrunch / RunaCapital)
# ========================
ross_2024 = [
    {"domain": "ollama.com", "company_name": "Ollama", "description": "Run LLMs locally - open source desktop AI"},
    {"domain": "zed.dev", "company_name": "Zed", "description": "High-performance collaborative code editor"},
    {"domain": "dify.ai", "company_name": "Dify", "description": "Open source LLM app development platform"},
    {"domain": "comfy.org", "company_name": "ComfyUI", "description": "Node-based AI image/video/audio generation"},
    {"domain": "all-hands.dev", "company_name": "All Hands AI", "description": "AI software development agents - OpenHands"},
    {"domain": "astral.sh", "company_name": "Astral", "description": "Python tooling - uv, ruff fast Rust-based tools"},
    {"domain": "stirlingpdf.com", "company_name": "Stirling PDF", "description": "PDF manipulation tool self-hosted"},
    {"domain": "maybe.co", "company_name": "Maybe Finance", "description": "Open source personal finance and wealth management"},
    {"domain": "fuel.network", "company_name": "Fuel Labs", "description": "Ethereum blockchain modular execution layer"},
    {"domain": "tabby.tabbyml.com", "company_name": "TabbyML", "description": "Open source self-hosted AI coding assistant"},
    {"domain": "langchain.com", "company_name": "LangChain", "description": "Framework for LLM-centric applications"},
    {"domain": "crewai.com", "company_name": "CrewAI", "description": "Multi-agent AI framework"},
    {"domain": "openinterpreter.com", "company_name": "Open Interpreter", "description": "Natural language interface for computers"},
    {"domain": "litellm.ai", "company_name": "LiteLLM", "description": "OpenAI-compatible API for 100+ LLMs"},
    {"domain": "qdrant.io", "company_name": "Qdrant", "description": "Vector database for AI"},
    {"domain": "chroma.run", "company_name": "Chroma", "description": "Open source embedding database"},
    {"domain": "milvus.io", "company_name": "Milvus", "description": "Open source vector database for AI"},
    {"domain": "weaviate.io", "company_name": "Weaviate", "description": "AI-native vector database"},
    {"domain": "lancedb.com", "company_name": "LanceDB", "description": "Developer-friendly AI vector database"},
    {"domain": "activeloop.ai", "company_name": "Activeloop", "description": "Deep Lake vector data lake"},
    {"domain": "trychroma.com", "company_name": "Chroma DB", "description": "The AI-native open-source embedding database"},
    {"domain": "openobserve.ai", "company_name": "OpenObserve", "description": "Open source observability platform"},
    {"domain": "bytebase.com", "company_name": "Bytebase", "description": "Database DevOps and CI/CD for teams"},
    {"domain": "opensearch.org", "company_name": "OpenSearch", "description": "Open source search and analytics"},
    {"domain": "mage.ai", "company_name": "Mage.ai", "description": "Data pipeline tool for ML and analytics"},
    {"domain": "marimo.io", "company_name": "Marimo", "description": "Reactive Python notebook"},
    {"domain": "evidence.dev", "company_name": "Evidence", "description": "BI as code - reports from SQL and markdown"},
    {"domain": "metriql.com", "company_name": "Metriql", "description": "Open source headless BI"},
    {"domain": "cube.dev", "company_name": "Cube", "description": "Semantic layer for building data apps"},
    {"domain": "risingwave.com", "company_name": "RisingWave", "description": "Distributed SQL stream processing database"},
    {"domain": "readyset.io", "company_name": "ReadySet", "description": "SQL caching layer for databases"},
    {"domain": "supabase.com", "company_name": "Supabase", "description": "Open source Firebase alternative"},
    {"domain": "turso.tech", "company_name": "Turso", "description": "Edge SQLite database"},
    {"domain": "electric-sql.com", "company_name": "ElectricSQL", "description": "Local-first sync layer for Postgres"},
    {"domain": "xata.io", "company_name": "Xata", "description": "Serverless data platform for Postgres"},
    {"domain": "fauna.com", "company_name": "Fauna", "description": "Distributed document-relational database"},
    {"domain": "singlestore.com", "company_name": "SingleStore", "description": "Distributed SQL database for analytics"},
    {"domain": "cockroachlabs.com", "company_name": "CockroachDB", "description": "Cloud-native distributed SQL"},
    {"domain": "materialize.com", "company_name": "Materialize", "description": "Streaming SQL database"},
    {"domain": "hydrolix.io", "company_name": "Hydrolix", "description": "Streaming data lake for log analytics"},
    {"domain": "tinybird.co", "company_name": "Tinybird", "description": "Real-time data pipelines and APIs"},
    {"domain": "hasura.io", "company_name": "Hasura", "description": "Instant GraphQL APIs on any database"},
    {"domain": "wundergraph.com", "company_name": "WunderGraph", "description": "API developer platform"},
    {"domain": "graphql-hive.com", "company_name": "GraphQL Hive", "description": "Open source GraphQL schema registry"},
    {"domain": "stellate.co", "company_name": "Stellate", "description": "GraphQL CDN and edge caching"},
    {"domain": "stepzen.com", "company_name": "StepZen", "description": "GraphQL API for backend developers"},
    {"domain": "grafbase.com", "company_name": "Grafbase", "description": "Edge-native GraphQL platform"},
    {"domain": "edgedb.com", "company_name": "EdgeDB", "description": "Graph-relational database"},
    {"domain": "convex.dev", "company_name": "Convex", "description": "Open source backend platform"},
    {"domain": "instantdb.com", "company_name": "InstantDB", "description": "Modern Firebase for the web"},
    {"domain": "zero.rocicorp.dev", "company_name": "Rocicorp Zero", "description": "Sync engine for local-first apps"},
    {"domain": "replicache.dev", "company_name": "Replicache", "description": "High-performance sync for collaborative web apps"},
    {"domain": "liveblocks.io", "company_name": "Liveblocks", "description": "Real-time collaboration APIs"},
    {"domain": "partykit.io", "company_name": "PartyKit", "description": "Platform for building realtime collaborative apps"},
    {"domain": "y-crdt.org", "company_name": "Yjs", "description": "CRDT framework for collaborative apps"},
    {"domain": "driftdb.com", "company_name": "DriftDB", "description": "Real-time data backend for web apps"},
    {"domain": "alchemy.com", "company_name": "Alchemy", "description": "Web3 development platform"},
    {"domain": "quicknode.com", "company_name": "QuickNode", "description": "Web3 infrastructure and development APIs"},
    {"domain": "infura.io", "company_name": "Infura", "description": "Ethereum and IPFS API infrastructure"},
    {"domain": "moralis.io", "company_name": "Moralis", "description": "Web3 development platform"},
    {"domain": "thirdweb.com", "company_name": "Thirdweb", "description": "Web3 development tools and SDKs"},
    {"domain": "privy.io", "company_name": "Privy", "description": "Auth and wallets for Web3 apps"},
    {"domain": "dynamic.xyz", "company_name": "Dynamic", "description": "Web3 auth and identity"},
    {"domain": "0xpass.io", "company_name": "0xPass", "description": "Web3 authentication protocol"},
    {"domain": "turnkey.com", "company_name": "Turnkey", "description": "Crypto wallet infrastructure"},
    {"domain": "dfns.io", "company_name": "Dfns", "description": "Crypto wallet-as-a-service"},
    {"domain": "fireblocks.com", "company_name": "Fireblocks", "description": "Digital asset infrastructure"},
    {"domain": "moonpay.com", "company_name": "MoonPay", "description": "Crypto on/off-ramp infrastructure"},
    {"domain": "transak.com", "company_name": "Transak", "description": "Web3 payment infrastructure"},
    {"domain": "ramp.network", "company_name": "Ramp Network", "description": "Fiat-crypto infrastructure"},
    {"domain": "simplex.com", "company_name": "Simplex", "description": "Crypto payments processing"},
    {"domain": "sardine.ai", "company_name": "Sardine", "description": "Fraud prevention and compliance for fintech"},
    {"domain": "unit21.ai", "company_name": "Unit21", "description": "Risk and compliance infrastructure"},
    {"domain": "persona.com", "company_name": "Persona", "description": "Identity verification platform"},
    {"domain": "alloy.com", "company_name": "Alloy", "description": "Identity decisioning for fintech"},
    {"domain": "jumio.com", "company_name": "Jumio", "description": "AI-powered identity verification"},
    {"domain": "onfido.com", "company_name": "Onfido", "description": "Identity verification and background checks"},
    {"domain": "sumsub.com", "company_name": "Sumsub", "description": "Full-cycle KYC/AML verification"},
    {"domain": "stripe.com", "company_name": "Stripe", "description": "Payment infrastructure for the internet"},
    {"domain": "adyen.com", "company_name": "Adyen", "description": "Global payment platform"},
    {"domain": "checkout.com", "company_name": "Checkout.com", "description": "Payment processing platform"},
    {"domain": "modern.treasury.com", "company_name": "Modern Treasury", "description": "Payment operations platform"},
    {"domain": "column.com", "company_name": "Column", "description": "Programmable bank built for developers"},
    {"domain": "treasury-prime.com", "company_name": "Treasury Prime", "description": "Banking-as-a-Service API"},
    {"domain": "synctera.com", "company_name": "Synctera", "description": "Banking-as-a-Service platform"},
    {"domain": "lithic.com", "company_name": "Lithic", "description": "Card issuing platform for developers"},
    {"domain": "marqeta.com", "company_name": "Marqeta", "description": "Card issuing and payment infrastructure"},
    {"domain": "highnote.com", "company_name": "Highnote", "description": "Embedded card payments platform"},
    {"domain": "increase.com", "company_name": "Increase", "description": "API-first bank for builders"},
    {"domain": "lead.bank", "company_name": "Lead Bank", "description": "Banking for fintechs"},
    {"domain": "plaid.com", "company_name": "Plaid", "description": "Financial data network for apps"},
    {"domain": "mx.com", "company_name": "MX", "description": "Financial data intelligence platform"},
    {"domain": "akoya.com", "company_name": "Akoya", "description": "Data access network for financial data"},
    {"domain": "finicity.com", "company_name": "Finicity", "description": "Open banking platform"},
    {"domain": "truelayer.com", "company_name": "TrueLayer", "description": "Open banking payment network"},
    {"domain": "yapily.com", "company_name": "Yapily", "description": "Open banking API connectivity"},
    {"domain": "tink.com", "company_name": "Tink", "description": "Open banking data platform"},
    {"domain": "nordigen.com", "company_name": "Nordigen", "description": "Free open banking data API"},
    {"domain": "basiq.io", "company_name": "Basiq", "description": "Financial data platform for Australia"},
    {"domain": "poweredbybalance.com", "company_name": "Balance", "description": "B2B payments infrastructure"},
    {"domain": "nuvei.com", "company_name": "Nuvei", "description": "Payment technology for businesses"},
    {"domain": "rapyd.com", "company_name": "Rapyd", "description": "Fintech-as-a-Service platform"},
    {"domain": "xendit.co", "company_name": "Xendit", "description": "Payment infrastructure for Southeast Asia"},
    {"domain": "razorpay.com", "company_name": "Razorpay", "description": "Payment gateway for businesses"},
    {"domain": "cashfree.com", "company_name": "Cashfree", "description": "Payment infrastructure for India"},
    {"domain": "paymongo.com", "company_name": "PayMongo", "description": "Payment gateway for Philippines"},
    {"domain": "paytabs.com", "company_name": "PayTabs", "description": "Payments platform for Middle East"},
    {"domain": "flutterwave.com", "company_name": "Flutterwave", "description": "Payments infrastructure for Africa"},
    {"domain": "paystack.com", "company_name": "Paystack", "description": "Payment gateway for Africa"},
    {"domain": "dlocal.com", "company_name": "dLocal", "description": "Payments platform for emerging markets"},
    {"domain": "nala.money", "company_name": "NALA", "description": "African fintech money transfer"},
    {"domain": "chipper.cash", "company_name": "Chipper Cash", "description": "Cross-border payments for Africa"},
    {"domain": "sendwave.com", "company_name": "Sendwave", "description": "International money transfer"},
    {"domain": "wise.com", "company_name": "Wise", "description": "International money transfers"},
    {"domain": "remitly.com", "company_name": "Remitly", "description": "Digital remittance platform"},
    {"domain": "lemonade.com", "company_name": "Lemonade", "description": "AI-powered insurance company"},
    {"domain": "hippo.com", "company_name": "Hippo", "description": "Home insurance platform"},
    {"domain": "wefox.com", "company_name": "Wefox", "description": "InsurTech platform"},
    {"domain": "bolttech.com", "company_name": "bolttech", "description": "Global embedded insurance platform"},
    {"domain": "coviesure.com", "company_name": "Coviesure", "description": "Embedded insurance platform"},
    {"domain": "socotra.com", "company_name": "Socotra", "description": "Cloud-native insurance platform"},
    {"domain": "guidewire.com", "company_name": "Guidewire", "description": "Insurance platform for P&C insurers"},
    {"domain": "majesco.com", "company_name": "Majesco", "description": "Insurance technology platform"},
    {"domain": "duck-creek.com", "company_name": "Duck Creek Technologies", "description": "Insurance SaaS platform"},
    {"domain": "sure.com", "company_name": "Sure", "description": "Embedded insurance platform"},
    {"domain": "foxquilt.com", "company_name": "Foxquilt", "description": "SMB commercial insurance platform"},
    {"domain": "tivly.com", "company_name": "Tivly", "description": "Commercial insurance marketplace"},
    {"domain": "next-insurance.com", "company_name": "Next Insurance", "description": "Small business insurance"},
    {"domain": "embroker.com", "company_name": "Embroker", "description": "Commercial insurance platform"},
    {"domain": "coalition.com", "company_name": "Coalition", "description": "Cyber insurance platform"},
    {"domain": "at-bay.com", "company_name": "At-Bay", "description": "Cyber insurance and security"},
    {"domain": "corvusinsurance.com", "company_name": "Corvus Insurance", "description": "AI-powered commercial insurance"},
    {"domain": "cowbell.insure", "company_name": "Cowbell Cyber", "description": "AI-driven cyber insurance"},
    {"domain": "resilience.com", "company_name": "Resilience", "description": "Cyber risk management and insurance"},
    {"domain": "axio.com", "company_name": "Axio", "description": "Cyber risk quantification"},
    {"domain": "bitsight.com", "company_name": "BitSight", "description": "Security ratings and cyber risk analytics"},
    {"domain": "securityscorecard.com", "company_name": "SecurityScorecard", "description": "Cybersecurity risk ratings"},
    {"domain": "panorays.com", "company_name": "Panorays", "description": "Third-party security risk management"},
    {"domain": "upguard.com", "company_name": "UpGuard", "description": "Cyber risk management"},
    {"domain": "whistic.com", "company_name": "Whistic", "description": "Vendor trust platform"},
    {"domain": "vanta.com", "company_name": "Vanta", "description": "Automated security compliance"},
    {"domain": "drata.com", "company_name": "Drata", "description": "Security and compliance automation"},
    {"domain": "secureframe.com", "company_name": "Secureframe", "description": "Security and compliance automation"},
    {"domain": "oneleet.com", "company_name": "Oneleet", "description": "Security compliance platform"},
    {"domain": "scytale.ai", "company_name": "Scytale", "description": "Automated compliance for SaaS"},
    {"domain": "sprinto.com", "company_name": "Sprinto", "description": "Automated security compliance"},
    {"domain": "compliancecow.com", "company_name": "ComplianceCow", "description": "Cloud compliance automation"},
    {"domain": "anecdotes.ai", "company_name": "Anecdotes.ai", "description": "Compliance operating system"},
    {"domain": "strike-graph.com", "company_name": "Strike Graph", "description": "Security certification and compliance"},
    {"domain": "hyperproof.io", "company_name": "Hyperproof", "description": "Compliance operations platform"},
    {"domain": "laika.com", "company_name": "Laika", "description": "Security and compliance platform"},
    {"domain": "thoropass.com", "company_name": "Thoropass", "description": "Compliance management platform"},
    {"domain": "trustero.com", "company_name": "Trustero", "description": "AI-powered GRC platform"},
    {"domain": "scrut.io", "company_name": "Scrut Automation", "description": "InfoSec and compliance management"},
    {"domain": "controlmap.io", "company_name": "ControlMap", "description": "Continuous control monitoring"},
    {"domain": "stackaware.com", "company_name": "StackAware", "description": "Open source risk quantification"},
    {"domain": "authomize.com", "company_name": "Authomize", "description": "Identity security platform"},
    {"domain": "entitle.io", "company_name": "Entitle", "description": "Cloud entitlements management"},
    {"domain": "teleport.sh", "company_name": "Teleport", "description": "Certificate-based access management"},
    {"domain": "boundary.hashicorp.com", "company_name": "HashiCorp Boundary", "description": "Secure remote access"},
    {"domain": "cyberark.com", "company_name": "CyberArk", "description": "Privileged access management"},
    {"domain": "beyondtrust.com", "company_name": "BeyondTrust", "description": "Privileged access management"},
    {"domain": "delinea.com", "company_name": "Delinea", "description": "Privileged access management"},
    {"domain": "keeper.io", "company_name": "Keeper Security", "description": "Zero-trust privileged access"},
    {"domain": "jumpcloud.com", "company_name": "JumpCloud", "description": "Open directory platform"},
    {"domain": "okta.com", "company_name": "Okta", "description": "Identity management and SSO"},
    {"domain": "auth0.com", "company_name": "Auth0", "description": "Identity platform for developers"},
    {"domain": "onelogin.com", "company_name": "OneLogin", "description": "Identity and access management"},
    {"domain": "duo.com", "company_name": "Duo Security", "description": "Multi-factor authentication"},
    {"domain": "yubico.com", "company_name": "Yubico", "description": "Hardware security keys"},
    {"domain": "hypersphere.id", "company_name": "Hypersphere", "description": "Decentralized identity platform"},
    {"domain": "spruceid.com", "company_name": "Spruce Systems", "description": "Decentralized identity tools"},
    {"domain": "mattr.global", "company_name": "MATTR", "description": "Decentralized identity platform"},
    {"domain": "trinsic.id", "company_name": "Trinsic", "description": "Verifiable credentials platform"},
    {"domain": "veridium.com", "company_name": "Veridium", "description": "Passwordless biometric authentication"},
    {"domain": "iproov.com", "company_name": "iProov", "description": "Biometric face verification"},
    {"domain": "callsign.com", "company_name": "Callsign", "description": "Digital trust intelligence"},
    {"domain": "telesign.com", "company_name": "TeleSign", "description": "Digital identity verification"},
    {"domain": "twilio.com", "company_name": "Twilio", "description": "Cloud communications platform"},
    {"domain": "bandwidth.com", "company_name": "Bandwidth", "description": "Communications API platform"},
    {"domain": "vonage.com", "company_name": "Vonage", "description": "Communications APIs for developers"},
    {"domain": "messagebird.com", "company_name": "MessageBird", "description": "Communications platform"},
    {"domain": "sinch.com", "company_name": "Sinch", "description": "Customer communications cloud"},
    {"domain": "infobip.com", "company_name": "Infobip", "description": "Omnichannel communications platform"},
    {"domain": "clicksend.com", "company_name": "ClickSend", "description": "SMS and communications API"},
    {"domain": "sendpulse.com", "company_name": "SendPulse", "description": "Multi-channel marketing automation"},
    {"domain": "textmagic.com", "company_name": "Textmagic", "description": "SMS marketing and communications"},
    {"domain": "routemobile.com", "company_name": "Route Mobile", "description": "CPaaS and messaging platform"},
    {"domain": "kaleyra.com", "company_name": "Kaleyra", "description": "Communications APIs platform"},
    {"domain": "plivo.com", "company_name": "Plivo", "description": "Cloud communications platform"},
    {"domain": "telnyx.com", "company_name": "Telnyx", "description": "Global communications network"},
    {"domain": "signalwire.com", "company_name": "SignalWire", "description": "Cloud communications platform"},
    {"domain": "lingo.media", "company_name": "Lingo.dev", "description": "AI-powered localization platform"},
    {"domain": "fiberplane.com", "company_name": "Fiberplane", "description": "Collaborative notebooks for SREs"},
    {"domain": "incident.io", "company_name": "Incident.io", "description": "Incident management platform"},
    {"domain": "rootly.com", "company_name": "Rootly", "description": "Incident management on Slack"},
    {"domain": "firehydrant.io", "company_name": "FireHydrant", "description": "Incident management platform"},
    {"domain": "pagerduty.com", "company_name": "PagerDuty", "description": "Digital operations management"},
    {"domain": "opsgenie.com", "company_name": "Opsgenie", "description": "Alert management and on-call scheduling"},
    {"domain": "victorops.com", "company_name": "VictorOps", "description": "Incident management platform"},
    {"domain": "alertmanager.io", "company_name": "Alertmanager", "description": "Prometheus alert management"},
    {"domain": "signl4.com", "company_name": "SIGNL4", "description": "Mobile alerting for teams"},
    {"domain": "statushero.com", "company_name": "Status Hero", "description": "Team standup and status updates"},
    {"domain": "geekbot.com", "company_name": "Geekbot", "description": "Async standups and surveys in Slack"},
    {"domain": "parabol.co", "company_name": "Parabol", "description": "Async agile meeting tool"},
    {"domain": "range.co", "company_name": "Range", "description": "Team check-in and async meetings"},
    {"domain": "standuply.com", "company_name": "Standuply", "description": "Async standups in Slack"},
    {"domain": "stretchly.app", "company_name": "Stretchly", "description": "Break time reminder app"},
    {"domain": "pomofocus.io", "company_name": "Pomofocus", "description": "Pomodoro timer app"},
    {"domain": "focusmate.com", "company_name": "Focusmate", "description": "Virtual coworking platform"},
    {"domain": "meco.app", "company_name": "Meco", "description": "Newsletter aggregator app"},
    {"domain": "readwise.io", "company_name": "Readwise", "description": "Spaced repetition for reading highlights"},
    {"domain": "speechify.com", "company_name": "Speechify", "description": "Text-to-speech reading tool"},
    {"domain": "recast.audio", "company_name": "Recast", "description": "AI-powered podcast summaries"},
    {"domain": "castbox.fm", "company_name": "Castbox", "description": "Podcast player and creator tool"},
    {"domain": "riverside.fm", "company_name": "Riverside.fm", "description": "Remote recording studio for podcasts"},
    {"domain": "descript.com", "company_name": "Descript", "description": "Video and podcast editing platform"},
    {"domain": "cleanvoice.ai", "company_name": "Cleanvoice", "description": "AI removes filler sounds from podcasts"},
    {"domain": "podcastle.ai", "company_name": "Podcastle", "description": "AI-powered podcast creation platform"},
    {"domain": "zencastr.com", "company_name": "Zencastr", "description": "Podcast recording and production"},
    {"domain": "anchor.fm", "company_name": "Anchor", "description": "Podcast creation and distribution"},
    {"domain": "buzzsprout.com", "company_name": "Buzzsprout", "description": "Podcast hosting platform"},
    {"domain": "transistor.fm", "company_name": "Transistor", "description": "Podcast hosting and analytics"},
    {"domain": "captivate.fm", "company_name": "Captivate", "description": "Podcast hosting and analytics"},
    {"domain": "simplecast.com", "company_name": "Simplecast", "description": "Podcast hosting and analytics"},
    {"domain": "podbean.com", "company_name": "Podbean", "description": "Podcast hosting and monetization"},
    {"domain": "spreaker.com", "company_name": "Spreaker", "description": "Podcast creation and distribution"},
    {"domain": "libsyn.com", "company_name": "Libsyn", "description": "Podcast hosting and distribution"},
    {"domain": "audioboom.com", "company_name": "Audioboom", "description": "Podcast network and hosting"},
    {"domain": "rss.com", "company_name": "RSS.com", "description": "Podcast hosting and distribution"},
    {"domain": "podcastics.com", "company_name": "Podcastics", "description": "Podcast hosting platform"},
    {"domain": "acast.com", "company_name": "Acast", "description": "Podcast platform for creators"},
    {"domain": "redcircle.com", "company_name": "RedCircle", "description": "Podcast platform with monetization"},
    {"domain": "castos.com", "company_name": "Castos", "description": "Podcast hosting and repurposing"},
    {"domain": "support.google.com", "company_name": "Google Podcasts", "description": "Podcast platform"},
    {"domain": "repodcast.io", "company_name": "Repodcast", "description": "Podcast guest booking platform"},
    {"domain": "podmatch.com", "company_name": "PodMatch", "description": "Podcast guest matching platform"},
    {"domain": "guestio.com", "company_name": "Guestio", "description": "Podcast booking platform"},
    {"domain": "wavve.co", "company_name": "Wavve", "description": "Turn podcast audio into shareable videos"},
    {"domain": "getaudiogram.com", "company_name": "Audiogram", "description": "Podcast audiogram creator"},
    {"domain": "stormy.fm", "company_name": "Stormy.fm", "description": "AI podcast summarizer"},
    {"domain": "podsqueeze.com", "company_name": "Podsqueeze", "description": "AI podcast content generator"},
    {"domain": "swell.ai", "company_name": "Swell AI", "description": "AI podcast content repurposing"},
    {"domain": "mightynetworks.com", "company_name": "Mighty Networks", "description": "Community platform for creators"},
    {"domain": "circle.so", "company_name": "Circle", "description": "Community platform for creators"},
    {"domain": "tribe.so", "company_name": "Betamode (Tribe)", "description": "Community platform"},
    {"domain": "hivebrite.com", "company_name": "Hivebrite", "description": "Community management platform"},
    {"domain": "bettermode.io", "company_name": "Bettermode", "description": "Customer community platform"},
    {"domain": "discourse.org", "company_name": "Discourse", "description": "Forum and community discussion platform"},
    {"domain": "flarum.org", "company_name": "Flarum", "description": "Open source forum platform"},
    {"domain": "nodebb.org", "company_name": "NodeBB", "description": "Node.js community forum platform"},
    {"domain": "khoros.com", "company_name": "Khoros", "description": "Community engagement platform"},
    {"domain": "lithium.com", "company_name": "Lithium Technologies", "description": "Community platform"},
    {"domain": "adereso.ai", "company_name": "Adereso", "description": "Conversational AI for business"},
    {"domain": "freshchat.com", "company_name": "Freshchat", "description": "Modern messaging software for teams"},
    {"domain": "tidio.com", "company_name": "Tidio", "description": "Live chat and chatbot platform"},
    {"domain": "tawk.to", "company_name": "tawk.to", "description": "Free live chat software"},
    {"domain": "crisp.chat", "company_name": "Crisp", "description": "Business messaging platform"},
    {"domain": "userlike.com", "company_name": "Userlike", "description": "Live chat for websites"},
    {"domain": "pure-chat.com", "company_name": "Pure Chat", "description": "Live chat software"},
    {"domain": "olark.com", "company_name": "Olark", "description": "Live chat for customer support"},
    {"domain": "livechatinc.com", "company_name": "LiveChat", "description": "Live chat support platform"},
    {"domain": "zendesk.com", "company_name": "Zendesk Chat", "description": "Live chat support"},
    {"domain": "snapengage.com", "company_name": "SnapEngage", "description": "Live chat and bot platform"},
    {"domain": "smartsupp.com", "company_name": "Smartsupp", "description": "Live chat with video recordings"},
    {"domain": "callbell.eu", "company_name": "Callbell", "description": "Multi-channel messaging for teams"},
    {"domain": "respond.io", "company_name": "Respond.io", "description": "Business messaging platform"},
    {"domain": "bird.com", "company_name": "Bird (MessageBird)", "description": "Omnichannel communications CRM"},
    {"domain": "gupshup.io", "company_name": "Gupshup", "description": "Conversational AI for enterprises"},
    {"domain": "verloop.io", "company_name": "Verloop", "description": "Conversational AI for customer support"},
    {"domain": "yellow.ai", "company_name": "Yellow.ai", "description": "Enterprise conversational AI platform"},
    {"domain": "uniphore.com", "company_name": "Uniphore", "description": "Conversational AI and automation"},
    {"domain": "nuance.com", "company_name": "Nuance", "description": "Conversational AI for enterprise"},
    {"domain": "speechworks.com", "company_name": "SpeechWorks", "description": "Voice and natural language AI"},
    {"domain": "rasa.com", "company_name": "Rasa", "description": "Open source conversational AI platform"},
    {"domain": "botpress.com", "company_name": "Botpress", "description": "Conversational AI platform"},
    {"domain": "voiceflow.com", "company_name": "Voiceflow", "description": "Conversational AI design platform"},
    {"domain": "landbot.io", "company_name": "Landbot", "description": "No-code chatbot builder"},
    {"domain": "manychat.com", "company_name": "ManyChat", "description": "Chat marketing automation platform"},
    {"domain": "chatfuel.com", "company_name": "Chatfuel", "description": "No-code chatbot for Facebook Messenger"},
    {"domain": "mobilemonkey.com", "company_name": "MobileMonkey", "description": "Multi-channel chatbot platform"},
    {"domain": "pandorabots.com", "company_name": "Pandorabots", "description": "Chatbot hosting platform"},
    {"domain": "flow.ai", "company_name": "Flow.ai", "description": "Enterprise chatbot platform"},
    {"domain": "kommunicate.io", "company_name": "Kommunicate", "description": "AI-powered customer support"},
    {"domain": "helpcrunch.com", "company_name": "HelpCrunch", "description": "Customer communication platform"},
    {"domain": "kayako.com", "company_name": "Kayako", "description": "Customer service and helpdesk"},
    {"domain": "helpscout.com", "company_name": "Help Scout", "description": "Customer support platform"},
    {"domain": "groove.hq", "company_name": "Groove", "description": "Helpdesk software for small businesses"},
    {"domain": "re-amaze.com", "company_name": "Re:amaze", "description": "Customer support and chat platform"},
    {"domain": "gorgias.io", "company_name": "Gorgias", "description": "E-commerce helpdesk platform"},
    {"domain": "gladly.com", "company_name": "Gladly", "description": "Customer service platform"},
    {"domain": "kustomer.com", "company_name": "Kustomer", "description": "AI-powered CRM for customer service"},
    {"domain": "dixa.com", "company_name": "Dixa", "description": "Customer service platform"},
    {"domain": "simplr.ai", "company_name": "Simplr", "description": "AI-powered customer service"},
    {"domain": "assembled.com", "company_name": "Assembled", "description": "Workforce management for support teams"},
    {"domain": "tymeshift.com", "company_name": "Tymeshift", "description": "Workforce management for Zendesk"},
    {"domain": "playvs.com", "company_name": "PlayVS", "description": "High school esports platform"},
    {"domain": "overwolf.com", "company_name": "Overwolf", "description": "Platform for in-game apps and mods"},
    {"domain": "streamelements.com", "company_name": "StreamElements", "description": "Tools for streamers and creators"},
    {"domain": "streamlabs.com", "company_name": "Streamlabs", "description": "Streaming software and tools"},
    {"domain": "restream.io", "company_name": "Restream", "description": "Multistream to multiple platforms"},
    {"domain": "splitmedialabs.com", "company_name": "XSplit", "description": "Streaming and recording software"},
    {"domain": "ecamm.com", "company_name": "Ecamm", "description": "Live streaming for Mac"},
    {"domain": "socialive.tv", "company_name": "Socialive", "description": "Enterprise live streaming platform"},
    {"domain": "switcher.studio", "company_name": "Switcher Studio", "description": "Mobile live video production"},
    {"domain": "streamyard.com", "company_name": "StreamYard", "description": "Browser-based live streaming studio"},
    {"domain": "melon.app", "company_name": "Melon", "description": "Live streaming tool for creators"},
    {"domain": "castr.io", "company_name": "Castr", "description": "Live streaming and video hosting"},
    {"domain": "dacast.com", "company_name": "Dacast", "description": "Enterprise video streaming platform"},
    {"domain": "kaltura.com", "company_name": "Kaltura", "description": "Video platform for enterprises"},
    {"domain": "jwplayer.com", "company_name": "JW Player", "description": "Video hosting and streaming platform"},
    {"domain": "brightcove.com", "company_name": "Brightcove", "description": "Video cloud services"},
    {"domain": "vimeo.com", "company_name": "Vimeo", "description": "Video hosting and streaming"},
    {"domain": "cloudflare.tv", "company_name": "Cloudflare Stream", "description": "Video streaming API"},
    {"domain": "mux.com", "company_name": "Mux", "description": "Video infrastructure for developers"},
    {"domain": "api.video", "company_name": "api.video", "description": "Video API for developers"},
    {"domain": "cloudinary.com", "company_name": "Cloudinary", "description": "Media management platform"},
    {"domain": "imagekit.io", "company_name": "ImageKit", "description": "Image and video optimization"},
    {"domain": "imgix.com", "company_name": "Imgix", "description": "Real-time image processing API"},
    {"domain": "uploadcare.com", "company_name": "Uploadcare", "description": "File uploading and processing API"},
    {"domain": "transloadit.com", "company_name": "Transloadit", "description": "File upload and encoding API"},
    {"domain": "filestack.com", "company_name": "Filestack", "description": "File upload API"},
    {"domain": "bytescale.com", "company_name": "Bytescale", "description": "File upload and storage API"},
    {"domain": "bunny.net", "company_name": "Bunny.net", "description": "CDN and edge storage"},
    {"domain": "fastly.com", "company_name": "Fastly", "description": "Edge cloud platform"},
    {"domain": "akamai.com", "company_name": "Akamai", "description": "Global CDN and cloud security"},
    {"domain": "cloudfront.net", "company_name": "AWS CloudFront", "description": "AWS CDN service"},
    {"domain": "keycdn.com", "company_name": "KeyCDN", "description": "Content delivery network"},
    {"domain": "stackpath.com", "company_name": "StackPath", "description": "Edge computing platform"},
    {"domain": "limelight.com", "company_name": "Limelight Networks", "description": "CDN and streaming services"},
    {"domain": "section.io", "company_name": "Section", "description": "Edge compute platform"},
    {"domain": "edg.io", "company_name": "Edgio", "description": "Edge cloud platform"},
    {"domain": "g-core.com", "company_name": "G-Core Labs", "description": "Edge network and CDN"},
    {"domain": "verizon.com", "company_name": "Verizon Media CDN", "description": "CDN and video streaming"},
    {"domain": "swarmcdn.com", "company_name": "SwarmCDN", "description": "P2P CDN"},
    {"domain": "peer5.com", "company_name": "Peer5", "description": "WebRTC CDN for live streaming"},
    {"domain": "bitmovin.com", "company_name": "Bitmovin", "description": "Video encoding and player SDK"},
    {"domain": "aws.amazon.com", "company_name": "AWS", "description": "Amazon Web Services cloud platform"},
    {"domain": "azure.microsoft.com", "company_name": "Azure", "description": "Microsoft cloud platform"},
    {"domain": "cloud.google.com", "company_name": "Google Cloud", "description": "Google cloud computing services"},
    {"domain": "digitalocean.com", "company_name": "DigitalOcean", "description": "Cloud infrastructure for developers"},
    {"domain": "linode.com", "company_name": "Linode (Akamai Cloud)", "description": "Cloud hosting platform"},
    {"domain": "vultr.com", "company_name": "Vultr", "description": "Cloud infrastructure and compute"},
    {"domain": "hetzner.com", "company_name": "Hetzner", "description": "Dedicated servers and cloud hosting"},
    {"domain": "ovhcloud.com", "company_name": "OVHcloud", "description": "Cloud and dedicated servers"},
    {"domain": "scaleway.com", "company_name": "Scaleway", "description": "Cloud provider for developers"},
    {"domain": "upcloud.com", "company_name": "UpCloud", "description": "Cloud hosting"},
    {"domain": "contabo.com", "company_name": "Contabo", "description": "VPS and dedicated servers"},
    {"domain": "kamatera.com", "company_name": "Kamatera", "description": "Global cloud infrastructure"},
    {"domain": "clouding.io", "company_name": "Clouding.io", "description": "Cloud servers"},
    {"domain": "ionos.com", "company_name": "IONOS", "description": "Web hosting and cloud services"},
    {"domain": "hostgator.com", "company_name": "HostGator", "description": "Web hosting services"},
    {"domain": "bluehost.com", "company_name": "Bluehost", "description": "Web hosting for WordPress"},
    {"domain": "siteground.com", "company_name": "SiteGround", "description": "Web hosting platform"},
    {"domain": "kinsta.com", "company_name": "Kinsta", "description": "Managed WordPress hosting"},
    {"domain": "wpengineer.com", "company_name": "WP Engine", "description": "WordPress hosting platform"},
    {"domain": "pantheon.io", "company_name": "Pantheon", "description": "WebOps platform for WordPress and Drupal"},
    {"domain": "platform.sh", "company_name": "Platform.sh", "description": "Cloud PaaS for web apps"},
    {"domain": "heroku.com", "company_name": "Heroku", "description": "Cloud platform as a service"},
    {"domain": "aptible.com", "company_name": "Aptible", "description": "HIPAA-compliant cloud platform"},
    {"domain": "northflank.com", "company_name": "Northflank", "description": "Developer platform for deploying services"},
    {"domain": "cyclic.sh", "company_name": "Cyclic", "description": "Serverless deployment for Node.js"},
    {"domain": "koyeb.com", "company_name": "Koyeb", "description": "Serverless deployment platform"},
    {"domain": "zeabur.com", "company_name": "Zeabur", "description": "One-click app deployment platform"},
    {"domain": "deno.com", "company_name": "Deno Deploy", "description": "Globally distributed JavaScript hosting"},
    {"domain": "workers.cloudflare.com", "company_name": "Cloudflare Workers", "description": "Serverless edge computing"},
    {"domain": "supabase.com", "company_name": "Supabase Edge Functions", "description": "Edge functions for Supabase"},
    {"domain": "val.town", "company_name": "Val Town", "description": "Social scripting network"},
    {"domain": "replit.com", "company_name": "Replit", "description": "Browser-based IDE and cloud dev"},
    {"domain": "codepen.io", "company_name": "CodePen", "description": "Online code editor for frontend"},
    {"domain": "codesandbox.io", "company_name": "CodeSandbox", "description": "Online IDE for web development"},
    {"domain": "stackblitz.com", "company_name": "StackBlitz", "description": "Online IDE for web development"},
    {"domain": "glitch.com", "company_name": "Glitch", "description": "Collaborative web app development"},
    {"domain": "jsfiddle.net", "company_name": "JSFiddle", "description": "Online JavaScript editor"},
    {"domain": "jsbin.com", "company_name": "JS Bin", "description": "Online JavaScript editor"},
    {"domain": "plnkr.co", "company_name": "Plunker", "description": "Web development tool"},
    {"domain": "vscode.dev", "company_name": "VS Code for Web", "description": "Browser-based VS Code"},
    {"domain": "cloud9ide.com", "company_name": "Cloud9 IDE", "description": "Cloud-based development environment"},
    {"domain": "theia-ide.org", "company_name": "Eclipse Theia", "description": "Cloud and desktop IDE"},
    {"domain": "codeanywhere.com", "company_name": "Codeanywhere", "description": "Cloud IDE for developers"},
    {"domain": "koding.com", "company_name": "Koding", "description": "Online development environments"},
    {"domain": "e2b.dev", "company_name": "E2B", "description": "Cloud sandbox for AI agents"},
    {"domain": "daytona.io", "company_name": "Daytona", "description": "Open source dev environment manager"},
    {"domain": "devpod.sh", "company_name": "DevPod", "description": "Open source dev environments"},
    {"domain": "coder.com", "company_name": "Coder", "description": "Cloud development environments"},
    {"domain": "shipyard.build", "company_name": "Shipyard", "description": "Ephemeral preview environments"},
    {"domain": "tugboat.qa", "company_name": "Tugboat", "description": "Preview environments for pull requests"},
    {"domain": "review-apps.com", "company_name": "Review Apps", "description": "Preview environments as a service"},
    {"domain": "vercel.com", "company_name": "Vercel Preview", "description": "Preview deployments"},
    {"domain": "netlify.com", "company_name": "Netlify Deploy Previews", "description": "Branch deploy previews"},
    {"domain": "doppler.com", "company_name": "Doppler", "description": "SecretOps platform"},
    {"domain": "cheqd.io", "company_name": "Cheqd", "description": "Trust layer for AI agents and credentials"},
    {"domain": "akka.io", "company_name": "Akka", "description": "Distributed systems toolkit"},
    {"domain": "temporal.io", "company_name": "Temporal", "description": "Durable execution for microservices"},
    {"domain": "conductor.netflix.com", "company_name": "Netflix Conductor", "description": "Microservices orchestration engine"},
    {"domain": "cadence.workflow", "company_name": "Cadence", "description": "Workflow orchestration engine"},
    {"domain": "zeebe.io", "company_name": "Zeebe", "description": "Workflow engine for microservices"},
    {"domain": "camunda.com", "company_name": "Camunda", "description": "Process automation platform"},
    {"domain": "flowable.com", "company_name": "Flowable", "description": "Intelligent process automation"},
    {"domain": "bonitasoft.com", "company_name": "Bonitasoft", "description": "Open source BPM platform"},
    {"domain": "processmaker.com", "company_name": "ProcessMaker", "description": "Intelligent process automation"},
    {"domain": "pipefy.com", "company_name": "Pipefy", "description": "Business process automation"},
    {"domain": "kissflow.com", "company_name": "Kissflow", "description": "No-code process and work management"},
    {"domain": "nintex.com", "company_name": "Nintex", "description": "Process management and automation"},
    {"domain": "workato.com", "company_name": "Workato", "description": "Enterprise automation platform"},
    {"domain": "tray.io", "company_name": "Tray.io", "description": "Enterprise automation platform"},
    {"domain": "make.com", "company_name": "Make (Integromat)", "description": "Visual automation platform"},
    {"domain": "zapier.com", "company_name": "Zapier", "description": "No-code automation platform"},
    {"domain": "integrately.com", "company_name": "Integrately", "description": "1-click app integrations"},
    {"domain": "pabbly.com", "company_name": "Pabbly Connect", "description": "Automation and workflow tool"},
    {"domain": "syncspider.com", "company_name": "SyncSpider", "description": "E-commerce data sync platform"},
    {"domain": "appdome.com", "company_name": "Appdome", "description": "Mobile app security platform"},
    {"domain": "guardsquare.com", "company_name": "GuardSquare", "description": "Mobile app security"},
    {"domain": "approov.io", "company_name": "Approov", "description": "Mobile API security"},
    {"domain": "talsec.app", "company_name": "Talsec", "description": "Mobile security platform"},
    {"domain": "inploi.com", "company_name": "Inploi", "description": "Talent acquisition infrastructure"},
    {"domain": "ashby.com", "company_name": "Ashby", "description": "All-in-one recruiting platform"},
    {"domain": "greenhouse.io", "company_name": "Greenhouse", "description": "Applicant tracking system"},
    {"domain": "lever.co", "company_name": "Lever", "description": "Recruiting platform and ATS"},
    {"domain": "workday.com", "company_name": "Workday", "description": "Enterprise HR and finance platform"},
    {"domain": "rippling.com", "company_name": "Rippling", "description": "HR and IT management platform"},
    {"domain": "gusto.com", "company_name": "Gusto", "description": "Payroll and HR platform"},
    {"domain": "deel.com", "company_name": "Deel", "description": "Global HR and payroll platform"},
    {"domain": "remote.com", "company_name": "Remote", "description": "Global HR platform"},
    {"domain": "oysterhr.com", "company_name": "Oyster HR", "description": "Global employment platform"},
    {"domain": "papayaglobal.com", "company_name": "Papaya Global", "description": "Global payroll platform"},
    {"domain": "mercury.com", "company_name": "Mercury", "description": "Banking for startups"},
    {"domain": "brex.com", "company_name": "Brex", "description": "Corporate cards and spend management"},
    {"domain": "ramp.com", "company_name": "Ramp", "description": "Corporate cards and spend management"},
    {"domain": "airbase.com", "company_name": "Airbase", "description": "Spend management platform"},
    {"domain": "spendesk.com", "company_name": "Spendesk", "description": "Spend management for businesses"},
    {"domain": "pleo.io", "company_name": "Pleo", "description": "Smart company cards for teams"},
    {"domain": "soldo.com", "company_name": "Soldo", "description": "Expense management for teams"},
    {"domain": "expensify.com", "company_name": "Expensify", "description": "Expense management software"},
    {"domain": "concursolutions.com", "company_name": "SAP Concur", "description": "Travel and expense management"},
    {"domain": "certify.com", "company_name": "Certify", "description": "Travel and expense management"},
    {"domain": "emburse.com", "company_name": "Emburse", "description": "Expense management suite"},
    {"domain": "birdieapp.ai", "company_name": "Birdie", "description": "AI-powered customer insights from reviews"},
    {"domain": "revuze.it", "company_name": "Revuze", "description": "AI consumer insights from reviews"},
    {"domain": "yotpo.com", "company_name": "Yotpo", "description": "Ecommerce marketing platform"},
    {"domain": "okendo.io", "company_name": "Okendo", "description": "Customer marketing platform"},
    {"domain": "stamped.io", "company_name": "Stamped.io", "description": "Reviews and loyalty for ecommerce"},
    {"domain": "judge.me", "company_name": "Judge.me", "description": "Product reviews for Shopify"},
    {"domain": "loox.io", "company_name": "Loox", "description": "Photo reviews for Shopify"},
    {"domain": "reviews.io", "company_name": "REVIEWS.io", "description": "Customer reviews platform"},
    {"domain": "trustpilot.com", "company_name": "Trustpilot", "description": "Business reviews platform"},
    {"domain": "g2.com", "company_name": "G2", "description": "Software reviews and discovery"},
    {"domain": "capterra.com", "company_name": "Capterra", "description": "Software reviews and comparison"},
    {"domain": "getapp.com", "company_name": "GetApp", "description": "Software marketplace and reviews"},
    {"domain": "software-advice.com", "company_name": "Software Advice", "description": "Software recommendations"},
    {"domain": "peerspot.com", "company_name": "PeerSpot", "description": "Enterprise software reviews"},
    {"domain": "techvalidate.com", "company_name": "TechValidate", "description": "Customer-generated content"},
    {"domain": "gartner.com", "company_name": "Gartner Peer Insights", "description": "Enterprise software reviews"},
    {"domain": "forrester.com", "company_name": "Forrester", "description": "Technology research and advisory"},
    {"domain": "idc.com", "company_name": "IDC", "description": "Technology market intelligence"},
    {"domain": "globaldata.com", "company_name": "GlobalData", "description": "Technology intelligence platform"},
    {"domain": "6sense.com", "company_name": "6sense", "description": "B2B revenue AI platform"},
    {"domain": "demandbase.com", "company_name": "Demandbase", "description": "B2B GTM platform"},
    {"domain": "bombora.com", "company_name": "Bombora", "description": "B2B intent data"},
    {"domain": "zoominfo.com", "company_name": "ZoomInfo", "description": "B2B sales intelligence platform"},
    {"domain": "lusha.com", "company_name": "Lusha", "description": "B2B sales intelligence"},
    {"domain": "hunter.io", "company_name": "Hunter.io", "description": "Email finder and verification"},
    {"domain": "clearbit.com", "company_name": "Clearbit", "description": "B2B data enrichment"},
    {"domain": "fullenrich.com", "company_name": "FullEnrich", "description": "B2B contact enrichment waterfall"},
    {"domain": "prospeo.io", "company_name": "Prospeo", "description": "Email finder from LinkedIn"},
    {"domain": "snov.io", "company_name": "Snov.io", "description": "Email finder and cold outreach"},
    {"domain": "seamless.ai", "company_name": "Seamless.AI", "description": "Sales prospecting platform"},
    {"domain": "cognism.com", "company_name": "Cognism", "description": "B2B sales intelligence"},
    {"domain": "rocketreach.co", "company_name": "RocketReach", "description": "Professional contact data"},
    {"domain": "contactout.com", "company_name": "ContactOut", "description": "Email finder for recruiters"},
    {"domain": "swordfish.ai", "company_name": "Swordfish", "description": "Contact data for outbound sales"},
    {"domain": "getprospect.com", "company_name": "GetProspect", "description": "Email finder tool"},
    {"domain": "anymailfinder.com", "company_name": "AnyMailFinder", "description": "Email finding service"},
    {"domain": "findthatlead.com", "company_name": "FindThatLead", "description": "Lead generation and email finder"},
    {"domain": "voilanorbert.com", "company_name": "Voila Norbert", "description": "Email finder"},
    {"domain": "dropcontact.com", "company_name": "Dropcontact", "description": "B2B email finder and enrichment"},
    {"domain": "skrapp.io", "company_name": "Skrapp", "description": "B2B email finder"},
    {"domain": "kaspr.io", "company_name": "Kaspr", "description": "Contact data platform"},
    {"domain": "waalaxy.com", "company_name": "Waalaxy", "description": "LinkedIn automation for prospecting"},
    {"domain": "evaboot.com", "company_name": "Evaboot", "description": "LinkedIn Sales Navigator export"},
    {"domain": "linkedhelper.com", "company_name": "LinkedHelper", "description": "LinkedIn automation tool"},
    {"domain": "dux-soup.com", "company_name": "Dux-Soup", "description": "LinkedIn lead generation tool"},
    {"domain": "expandi.io", "company_name": "Expandi", "description": "LinkedIn automation platform"},
    {"domain": "meets.ai", "company_name": "Meets.ai", "description": "AI-powered LinkedIn outreach"},
    {"domain": "salesrobot.co", "company_name": "SalesRobot", "description": "LinkedIn and email outreach automation"},
    {"domain": "skylead.io", "company_name": "Skylead", "description": "LinkedIn and email outreach"},
    {"domain": "hexospark.com", "company_name": "Hexospark", "description": "Email and LinkedIn outreach"},
    {"domain": "instantly.ai", "company_name": "Instantly.ai", "description": "Cold email automation platform"},
    {"domain": "lemlist.com", "company_name": "Lemlist", "description": "Cold outreach and sales automation"},
    {"domain": "mailshake.com", "company_name": "Mailshake", "description": "Cold email and sales engagement"},
    {"domain": "reply.io", "company_name": "Reply.io", "description": "Sales engagement platform"},
    {"domain": "woodpecker.co", "company_name": "Woodpecker", "description": "Cold email for B2B companies"},
    {"domain": "quickmail.io", "company_name": "QuickMail", "description": "Cold email automation"},
    {"domain": "saleshub.ai", "company_name": "SalesHub", "description": "AI sales engagement platform"},
    {"domain": "klenty.com", "company_name": "Klenty", "description": "Sales engagement platform"},
    {"domain": "yesware.com", "company_name": "Yesware", "description": "Email tracking for sales"},
    {"domain": "mixmax.com", "company_name": "Mixmax", "description": "Email productivity for sales"},
    {"domain": "boomeranggmail.com", "company_name": "Boomerang", "description": "Email productivity tool"},
    {"domain": "superhuman.com", "company_name": "Superhuman", "description": "AI-powered email client"},
    {"domain": "mimestream.com", "company_name": "Mimestream", "description": "Gmail client for Mac"},
    {"domain": "airmail5.com", "company_name": "Airmail", "description": "Email client for Apple devices"},
    {"domain": "heylo.com", "company_name": "Hey.com", "description": "Email reimagined by Basecamp"},
    {"domain": "fastmail.com", "company_name": "Fastmail", "description": "Private email service"},
    {"domain": "proton.me", "company_name": "Proton Mail", "description": "Encrypted email service"},
    {"domain": "tutanota.com", "company_name": "Tutanota", "description": "Encrypted email service"},
    {"domain": "skiff.com", "company_name": "Skiff", "description": "Privacy-first documents and email"},
    {"domain": "maildrop.cc", "company_name": "Maildrop", "description": "Disposable email service"},
    {"domain": "guerrillamail.com", "company_name": "Guerrilla Mail", "description": "Disposable email service"},
    {"domain": "temp-mail.org", "company_name": "Temp Mail", "description": "Temporary email service"},
    {"domain": "mailsac.com", "company_name": "Mailsac", "description": "Disposable email service for developers"},
    {"domain": "mailtrap.io", "company_name": "Mailtrap", "description": "Email sandbox for developers"},
    {"domain": "ethereal.email", "company_name": "Ethereal Email", "description": "Fake SMTP server for testing"},
    {"domain": "litmus.com", "company_name": "Litmus", "description": "Email testing and analytics"},
    {"domain": "email-on-acid.com", "company_name": "Email on Acid", "description": "Email testing platform"},
    {"domain": "mailninja.co", "company_name": "MailNinja", "description": "Email marketing platform"},
    {"domain": "sendx.io", "company_name": "SendX", "description": "Email marketing platform"},
    {"domain": "flodesk.com", "company_name": "Flodesk", "description": "Email marketing for creators"},
    {"domain": "emailoctopus.com", "company_name": "EmailOctopus", "description": "Email marketing platform"},
    {"domain": "campaignmonitor.com", "company_name": "Campaign Monitor", "description": "Email marketing platform"},
    {"domain": "benchmark.email", "company_name": "Benchmark Email", "description": "Email marketing platform"},
    {"domain": "icontact.com", "company_name": "iContact", "description": "Email marketing platform"},
    {"domain": "mailercloud.com", "company_name": "Mailercloud", "description": "Email marketing platform"},
    {"domain": "listek.com", "company_name": "Listek", "description": "Email marketing platform"},
    {"domain": "verticalresponse.com", "company_name": "VerticalResponse", "description": "Email marketing for small businesses"},
    {"domain": "contactpigeon.com", "company_name": "ContactPigeon", "description": "Marketing automation for e-commerce"},
    {"domain": "autopilot.com", "company_name": "Ortto (Autopilot)", "description": "Marketing automation platform"},
    {"domain": "encharge.io", "company_name": "Encharge", "description": "Marketing automation for SaaS"},
    {"domain": "userlist.com", "company_name": "Userlist", "description": "Email marketing for SaaS companies"},
    {"domain": "appsignal.com", "company_name": "AppSignal", "description": "Application monitoring and APM"},
    {"domain": "bugsnag.com", "company_name": "Bugsnag", "description": "Application stability management"},
    {"domain": "airbrake.io", "company_name": "Airbrake", "description": "Error monitoring for developers"},
    {"domain": "rollbar.com", "company_name": "Rollbar", "description": "Error monitoring platform"},
    {"domain": "raygun.com", "company_name": "Raygun", "description": "Application performance and error monitoring"},
    {"domain": "elmah.io", "company_name": "ELMAH.io", "description": "Cloud error logging for .NET"},
    {"domain": "honeybadger.io", "company_name": "Honeybadger", "description": "Application health monitoring"},
    {"domain": "exceptionless.com", "company_name": "Exceptionless", "description": "Real-time error tracking"},
    {"domain": "lightrun.com", "company_name": "Lightrun", "description": "Continuous observability for developers"},
    {"domain": "rookout.com", "company_name": "Rookout", "description": "Live debugging and observability"},
    {"domain": "rookout.com", "company_name": "Rookout", "description": "Debug production code live"},
    {"domain": "digma.ai", "company_name": "Digma", "description": "Continuous feedback for developers"},
    {"domain": "speedscale.com", "company_name": "Speedscale", "description": "API testing with real traffic"},
    {"domain": "loadmill.com", "company_name": "Loadmill", "description": "AI-powered load testing"},
    {"domain": "k6.io", "company_name": "Grafana k6", "description": "Open source load testing"},
    {"domain": "gatling.io", "company_name": "Gatling", "description": "Load testing tool"},
    {"domain": "locust.io", "company_name": "Locust", "description": "Open source load testing"},
    {"domain": "artillery.io", "company_name": "Artillery", "description": "Cloud-scale load testing"},
    {"domain": "flood.io", "company_name": "Flood.io", "description": "Load testing cloud"},
    {"domain": "blazemeter.com", "company_name": "BlazeMeter", "description": "Cloud-based performance testing"},
    {"domain": "neoload.com", "company_name": "NeoLoad", "description": "Performance testing platform"},
    {"domain": "apica.io", "company_name": "Apica", "description": "Load testing and monitoring"},
    {"domain": "loader.io", "company_name": "Loader.io", "description": "Cloud-based load testing"},
    {"domain": "octoperf.com", "company_name": "OctoPerf", "description": "JMeter-based load testing SaaS"},
    {"domain": "testgrid.io", "company_name": "TestGrid", "description": "AI-powered test automation"},
    {"domain": "testim.io", "company_name": "Testim", "description": "AI-based test automation"},
    {"domain": "mabl.com", "company_name": "Mabl", "description": "Intelligent test automation"},
    {"domain": "functionize.com", "company_name": "Functionize", "description": "AI-powered testing platform"},
    {"domain": "autify.com", "company_name": "Autify", "description": "No-code test automation"},
    {"domain": "reflect.run", "company_name": "Reflect", "description": "No-code automated testing"},
    {"domain": "waldo.com", "company_name": "Waldo", "description": "No-code mobile testing"},
    {"domain": "bugbug.io", "company_name": "BugBug", "description": "Simple browser test automation"},
    {"domain": "cypress.io", "company_name": "Cypress", "description": "JavaScript end-to-end testing"},
    {"domain": "playwright.dev", "company_name": "Playwright", "description": "Browser automation and testing"},
    {"domain": "browserstack.com", "company_name": "BrowserStack", "description": "Cross-browser testing platform"},
    {"domain": "lambdatest.com", "company_name": "LambdaTest", "description": "Cloud testing platform"},
    {"domain": "saucelabs.com", "company_name": "Sauce Labs", "description": "Cloud testing platform"},
    {"domain": "testingbot.com", "company_name": "TestingBot", "description": "Cross-browser and mobile testing"},
    {"domain": "crossbrowsertesting.com", "company_name": "CrossBrowserTesting", "description": "Browser compatibility testing"},
    {"domain": "browserless.io", "company_name": "Browserless", "description": "Headless Chrome API"},
    {"domain": "apify.com", "company_name": "Apify", "description": "Web scraping and automation platform"},
    {"domain": "scrapfly.io", "company_name": "Scrapfly", "description": "Web scraping API"},
    {"domain": "crawlbase.com", "company_name": "Crawlbase", "description": "Data scraping and crawling API"},
    {"domain": "scraperapi.com", "company_name": "ScraperAPI", "description": "Web scraping API"},
    {"domain": "scrapingbee.com", "company_name": "ScrapingBee", "description": "Web scraping API"},
    {"domain": "brightdata.com", "company_name": "Bright Data", "description": "Web data platform and proxy network"},
    {"domain": "proxycrawl.com", "company_name": "ProxyCrawl", "description": "Web scraping and proxy API"},
    {"domain": "abstractapi.com", "company_name": "Abstract API", "description": "Collection of developer APIs"},
    {"domain": "ipinfo.io", "company_name": "IPinfo", "description": "IP address data API"},
    {"domain": "maxmind.com", "company_name": "MaxMind", "description": "IP geolocation and fraud detection"},
    {"domain": "ipstack.com", "company_name": "ipstack", "description": "IP geolocation API"},
    {"domain": "ipgeolocation.io", "company_name": "IP Geolocation API", "description": "IP address geolocation"},
    {"domain": "ipdata.co", "company_name": "ipdata", "description": "IP address intelligence API"},
    {"domain": "ip-api.com", "company_name": "ip-api", "description": "Free IP geolocation API"},
    {"domain": "ipwhois.io", "company_name": "ipwhois", "description": "IP data API"},
    {"domain": "ipregistry.co", "company_name": "ipregistry", "description": "IP geolocation API"},
    {"domain": "openaq.org", "company_name": "OpenAQ", "description": "Air quality data platform"},
    {"domain": "tomorrow.io", "company_name": "Tomorrow.io", "description": "Weather intelligence platform"},
    {"domain": "climacell.co", "company_name": "Tomorrow.io (ClimaCell)", "description": "Hyperlocal weather API"},
    {"domain": "weatherapi.com", "company_name": "WeatherAPI", "description": "Weather data API"},
    {"domain": "openweathermap.org", "company_name": "OpenWeatherMap", "description": "Weather data API"},
    {"domain": "stormglass.io", "company_name": "Stormglass", "description": "Marine and weather API"},
    {"domain": "aerisweather.com", "company_name": "AerisWeather", "description": "Weather data platform"},
    {"domain": "foreca.com", "company_name": "Foreca", "description": "Weather forecasting API"},
    {"domain": "visualcrossing.com", "company_name": "Visual Crossing", "description": "Historical weather data API"},
    {"domain": "meteomatics.com", "company_name": "Meteomatics", "description": "Weather data API"},
    {"domain": "theweathernetwork.com", "company_name": "The Weather Network", "description": "Weather data and forecasts"},
    {"domain": "weatherbit.io", "company_name": "Weatherbit", "description": "Weather API"},
    {"domain": "pirateweather.net", "company_name": "Pirate Weather", "description": "Open source weather API"},
    {"domain": "open-meteo.com", "company_name": "Open-Meteo", "description": "Free open source weather API"},
]

# ========================
# SOURCE: awesome-product-hunt (developer tools)
# ========================
product_hunt_devtools = [
    {"domain": "edgee.cloud", "company_name": "Edgee", "description": "Claude Code compressor for developers"},
    {"domain": "superset.ai", "company_name": "Superset AI", "description": "Run AI coding agents on your machine"},
    {"domain": "mastra.ai", "company_name": "Mastra", "description": "TypeScript AI agent framework"},
    {"domain": "tessl.io", "company_name": "Tessl", "description": "AI coding agent optimization"},
    {"domain": "kiloclaw.com", "company_name": "KiloClaw", "description": "Hosted OpenClaw service"},
    {"domain": "layercode.com", "company_name": "Layercode", "description": "Build voice AI agents"},
    {"domain": "qa.tech", "company_name": "QA.tech", "description": "AI QA testing agents"},
    {"domain": "thesys.dev", "company_name": "Thesys", "description": "AI apps with interactive UI"},
    {"domain": "kilocode.ai", "company_name": "Kilo Code", "description": "Open source AI coding agent"},
    {"domain": "aikido.dev", "company_name": "Aikido Security", "description": "Security for everything you build"},
    {"domain": "tempo.new", "company_name": "Tempo Labs", "description": "Visual editor for React with AI"},
    {"domain": "reflex.dev", "company_name": "Reflex", "description": "Build web apps in pure Python"},
    {"domain": "lovable.dev", "company_name": "Lovable", "description": "AI full stack engineer for apps"},
    {"domain": "trench.dev", "company_name": "Trench", "description": "Open source analytics infrastructure"},
    {"domain": "bolt.new", "company_name": "Bolt.new", "description": "AI-powered full-stack web app builder"},
    {"domain": "trag.dev", "company_name": "Trag", "description": "AI code review companion"},
    {"domain": "getlatitude.ai", "company_name": "Latitude", "description": "Open source prompt engineering platform"},
    {"domain": "helicone.ai", "company_name": "Helicone AI", "description": "Open source LLM observability"},
    {"domain": "inkeep.com", "company_name": "Inkeep", "description": "AI search and support from your content"},
    {"domain": "subframe.com", "company_name": "Subframe", "description": "Best way to build UI fast"},
    {"domain": "daytona.io", "company_name": "Daytona", "description": "Dev environment manager"},
    {"domain": "octomind.dev", "company_name": "Octomind", "description": "AI-powered bug finding"},
    {"domain": "corbado.com", "company_name": "Corbado", "description": "Passkey-first authentication"},
    {"domain": "openmeter.io", "company_name": "OpenMeter", "description": "Usage metering for engineers"},
    {"domain": "lastmileai.dev", "company_name": "LastMile AI", "description": "AI developer platform for engineering teams"},
    {"domain": "graphite.dev", "company_name": "Graphite", "description": "How the fastest developers ship code"},
    {"domain": "mintlify.com", "company_name": "Mintlify", "description": "Documentation platform for developers"},
    {"domain": "warp.dev", "company_name": "Warp", "description": "Terminal for the 21st century"},
    {"domain": "specify.io", "company_name": "Specify", "description": "Sync design tokens with code"},
    {"domain": "lingo.dev", "company_name": "Lingo.dev", "description": "Ship apps translated in every language"},
    {"domain": "logo.dev", "company_name": "Logo.dev", "description": "Reliable logos API for any company"},
    {"domain": "cubic.dev", "company_name": "Cubic", "description": "Cursor for code review"},
    {"domain": "twelvelabs.io", "company_name": "TwelveLabs", "description": "Video understanding AI platform"},
    {"domain": "layouts.dev", "company_name": "Layouts.dev", "description": "Notebook for building interfaces with Tailwind"},
    {"domain": "typo.ai", "company_name": "Typo", "description": "Better code and faster deployments"},
    {"domain": "openmeteo.com", "company_name": "Open-Meteo", "description": "Free weather API"},
    {"domain": "raycast.com", "company_name": "Raycast", "description": "Supercharged Mac productivity tool"},
    {"domain": "tonkotsu.ai", "company_name": "Tonkotsu", "description": "Manage coding agents from a doc"},
    {"domain": "usejolt.ai", "company_name": "Jolt AI", "description": "AI assistant for large codebases"},
]

# ========================
# SOURCE: Rails/Next.js startups mentioned in searches
# ========================
framework_startups = [
    {"domain": "craftwork.com", "company_name": "Craftwork", "description": "Home painting company - Rails"},
    {"domain": "whop.com", "company_name": "Whop", "description": "Digital marketplace for creators"},
    {"domain": "playbook.com", "company_name": "Playbook", "description": "Creative asset management"},
    {"domain": "fountain.com", "company_name": "Fountain", "description": "High-volume hiring automation"},
    {"domain": "monograph.com", "company_name": "Monograph", "description": "Project management for architects"},
    {"domain": "bannerbear.com", "company_name": "Bannerbear", "description": "Auto-generate social media visuals"},
    {"domain": "craftwork.com", "company_name": "Craftwork", "description": "Home improvement marketplace"},
    {"domain": "flexcar.com", "company_name": "Flexcar", "description": "Car subscription service"},
    {"domain": "stackblitz.com", "company_name": "StackBlitz", "description": "Online IDE for web development"},
    {"domain": "growthlist.co", "company_name": "GrowthList", "description": "List of funded SaaS startups"},
    {"domain": "qwikchek.com", "company_name": "QwikChek", "description": "Web vulnerability scanning tool"},
    {"domain": "vocalize.cloud", "company_name": "Vocalize Cloud", "description": "Voice synthesis platform"},
    {"domain": "openbb.finance", "company_name": "OpenBB Terminal", "description": "Open source investment research"},
    {"domain": "simpleanalytics.com", "company_name": "Simple Analytics", "description": "Privacy-first web analytics"},
    {"domain": "fathom.net", "company_name": "Fathom Analytics", "description": "Privacy-focused website analytics"},
    {"domain": "pirsch.io", "company_name": "Pirsch", "description": "Cookie-free website analytics"},
    {"domain": "counter.dev", "company_name": "Counter.dev", "description": "Simple web analytics"},
    {"domain": "splitbee.io", "company_name": "Splitbee", "description": "Analytics and A/B testing"},
    {"domain": "piwik.pro", "company_name": "Piwik PRO", "description": "Privacy-compliant analytics"},
    {"domain": "woorank.com", "company_name": "WooRank", "description": "Website review and SEO tool"},
    {"domain": "seobility.net", "company_name": "Seobility", "description": "SEO software"},
    {"domain": "ahrefs.com", "company_name": "Ahrefs", "description": "SEO toolset and backlink checker"},
    {"domain": "semrush.com", "company_name": "SEMrush", "description": "Digital marketing and SEO platform"},
    {"domain": "moz.com", "company_name": "Moz", "description": "SEO software and tools"},
    {"domain": "majestic.com", "company_name": "Majestic", "description": "SEO backlink checker"},
    {"domain": "screamingfrog.co.uk", "company_name": "Screaming Frog", "description": "SEO spider tool"},
    {"domain": "sitebulb.com", "company_name": "Sitebulb", "description": "Website auditing tool"},
    {"domain": "serpstat.com", "company_name": "Serpstat", "description": "All-in-one SEO platform"},
    {"domain": "spyfu.com", "company_name": "SpyFu", "description": "Competitor keyword research"},
    {"domain": "similarweb.com", "company_name": "SimilarWeb", "description": "Digital intelligence platform"},
    {"domain": "surfer.seo", "company_name": "Surfer SEO", "description": "Content optimization for SEO"},
    {"domain": "clearscope.io", "company_name": "Clearscope", "description": "Content optimization platform"},
    {"domain": "marketmuse.com", "company_name": "MarketMuse", "description": "Content intelligence platform"},
    {"domain": "frase.io", "company_name": "Frase", "description": "AI content creation and SEO"},
    {"domain": "jasper.ai", "company_name": "Jasper", "description": "AI content marketing platform"},
    {"domain": "copy.ai", "company_name": "Copy.ai", "description": "AI copywriting tool"},
    {"domain": "writesonic.com", "company_name": "Writesonic", "description": "AI writing assistant"},
    {"domain": "rytr.me", "company_name": "Rytr", "description": "AI writing assistant"},
    {"domain": "hypotenuse.ai", "company_name": "Hypotenuse AI", "description": "AI content generation"},
    {"domain": "scalenut.com", "company_name": "Scalenut", "description": "AI-powered content creation"},
    {"domain": "longshot.ai", "company_name": "LongShot AI", "description": "AI content creation for SEO"},
    {"domain": "peppertype.ai", "company_name": "Peppertype AI", "description": "AI content generation"},
    {"domain": "nichesss.com", "company_name": "Nichesss", "description": "AI marketing copy generator"},
    {"domain": "craftly.ai", "company_name": "Craftly.AI", "description": "AI writing assistant"},
    {"domain": "aiseo.ai", "company_name": "AISEO", "description": "AI-powered SEO content writing"},
    {"domain": "neuroflash.com", "company_name": "neuroflash", "description": "AI marketing text generator"},
    {"domain": "typeai.com", "company_name": "Type AI", "description": "AI text editor"},
    {"domain": "anyword.com", "company_name": "Anyword", "description": "AI writing platform with analytics"},
    {"domain": "persado.com", "company_name": "Persado", "description": "AI language for marketing"},
    {"domain": "phrasee.co", "company_name": "Phrasee", "description": "AI for brand language"},
    {"domain": "writer.com", "company_name": "Writer", "description": "AI writing platform for enterprises"},
    {"domain": "textio.com", "company_name": "Textio", "description": "AI writing for HR teams"},
    {"domain": "grammarly.com", "company_name": "Grammarly", "description": "AI writing assistant"},
    {"domain": "prowritingaid.com", "company_name": "ProWritingAid", "description": "AI writing editor"},
    {"domain": "hemingwayapp.com", "company_name": "Hemingway App", "description": "Writing editor for clarity"},
    {"domain": "wordtune.com", "company_name": "Wordtune", "description": "AI reading and writing companion"},
    {"domain": "lex.page", "company_name": "Lex", "description": "AI word processor"},
    {"domain": "notion.so", "company_name": "Notion AI", "description": "AI in your workspace"},
    {"domain": "coda.io", "company_name": "Coda AI", "description": "AI in your doc"},
    {"domain": "ai.google.dev", "company_name": "Google AI Studio", "description": "AI development platform"},
    {"domain": "anthropic.com", "company_name": "Anthropic", "description": "AI safety company - Claude"},
    {"domain": "cohere.ai", "company_name": "Cohere", "description": "AI language models for enterprises"},
    {"domain": "ai21.com", "company_name": "AI21 Labs", "description": "NLP AI platform"},
    {"domain": "alephalpha.com", "company_name": "Aleph Alpha", "description": "European AI research company"},
    {"domain": "mistral.ai", "company_name": "Mistral AI", "description": "Open weight language models"},
    {"domain": "inflection.ai", "company_name": "Inflection AI", "description": "Personal AI assistant"},
    {"domain": "adept.ai", "company_name": "Adept AI", "description": "AI agents for workflows"},
    {"domain": "imbue.com", "company_name": "Imbue", "description": "AI agents with robust reasoning"},
    {"domain": "characterai.com", "company_name": "Character.AI", "description": "AI characters for conversation"},
    {"domain": "poe.com", "company_name": "Poe", "description": "AI chatbot platform"},
    {"domain": "perplexity.ai", "company_name": "Perplexity AI", "description": "AI-powered search engine"},
    {"domain": "you.com", "company_name": "You.com", "description": "AI search engine"},
    {"domain": "phind.com", "company_name": "Phind", "description": "AI search for developers"},
    {"domain": "kagi.com", "company_name": "Kagi", "description": "Premium search engine"},
    {"domain": "neeva.com", "company_name": "Neeva", "description": "Ad-free search engine"},
    {"domain": "ecosia.org", "company_name": "Ecosia", "description": "Search engine that plants trees"},
    {"domain": "brave.com", "company_name": "Brave Search", "description": "Privacy-focused search engine"},
    {"domain": "duckduckgo.com", "company_name": "DuckDuckGo", "description": "Privacy-focused search engine"},
    {"domain": "startpage.com", "company_name": "Startpage", "description": "Private Google search"},
    {"domain": "mojeek.com", "company_name": "Mojeek", "description": "Independent search engine"},
    {"domain": "swisscows.com", "company_name": "Swisscows", "description": "Privacy-respecting search engine"},
    {"domain": "searx.org", "company_name": "SearX", "description": "Open source metasearch engine"},
    {"domain": "entrypoint.ai", "company_name": "Entrypoint AI", "description": "AI prompt management platform"},
    {"domain": "humanloop.com", "company_name": "Humanloop", "description": "AI model evaluation and fine-tuning"},
    {"domain": "scale.com", "company_name": "Scale AI", "description": "AI data platform"},
    {"domain": "snorkel.ai", "company_name": "Snorkel AI", "description": "AI data development platform"},
    {"domain": "labelbox.com", "company_name": "Labelbox", "description": "Data labeling and training platform"},
    {"domain": "encord.com", "company_name": "Encord", "description": "AI data development platform"},
    {"domain": "superannotate.com", "company_name": "SuperAnnotate", "description": "AI training data platform"},
    {"domain": "dataloop.ai", "company_name": "Dataloop", "description": "Data management and annotation"},
    {"domain": "clarifai.com", "company_name": "Clarifai", "description": "Full-stack AI platform"},
    {"domain": "roboflow.com", "company_name": "Roboflow", "description": "Computer vision platform"},
    {"domain": "landing.ai", "company_name": "Landing AI", "description": "AI for visual inspection"},
    {"domain": "comet.ml", "company_name": "Comet", "description": "AI and ML experiment tracking"},
    {"domain": "neptune.ai", "company_name": "Neptune.ai", "description": "ML experiment management"},
    {"domain": "mlflow.org", "company_name": "MLflow", "description": "Open source ML lifecycle platform"},
    {"domain": "dvc.org", "company_name": "Iterative", "description": "ML versioning and pipelines"},
    {"domain": "huggingface.co", "company_name": "Hugging Face", "description": "AI model hosting and collaboration"},
    {"domain": "wandb.ai", "company_name": "Weights & Biases", "description": "ML experiment tracking and visualization"},
    {"domain": "paperspace.com", "company_name": "Paperspace", "description": "Cloud GPU platform for ML"},
    {"domain": "modal.com", "company_name": "Modal", "description": "Cloud for AI/ML applications"},
    {"domain": "banana.dev", "company_name": "Banana.dev", "description": "Serverless GPU deployment"},
    {"domain": "baseten.co", "company_name": "Baseten", "description": "ML model serving platform"},
    {"domain": "beam.cloud", "company_name": "Beam", "description": "Serverless GPU for AI developers"},
    {"domain": "mystic.ai", "company_name": "Mystic.ai", "description": "ML deployment for any cloud"},
    {"domain": "cortex.dev", "company_name": "Cortex", "description": "Production ML infrastructure"},
    {"domain": "gradient.ai", "company_name": "Gradient", "description": "AI private deployment platform"},
    {"domain": "replicate.com", "company_name": "Replicate", "description": "Run AI models in the cloud"},
    {"domain": "fal.ai", "company_name": "fal.ai", "description": "Fast inference for AI models"},
    {"domain": "together.ai", "company_name": "Together AI", "description": "Fast inference for open source AI"},
    {"domain": "fireworks.ai", "company_name": "Fireworks AI", "description": "Fast inference for generative AI"},
    {"domain": "groq.com", "company_name": "Groq", "description": "Fastest LLM inference chips"},
    {"domain": "cerebras.ai", "company_name": "Cerebras", "description": "AI compute hardware and cloud"},
    {"domain": "sambanova.ai", "company_name": "SambaNova", "description": "AI chip and systems company"},
    {"domain": "graphcore.ai", "company_name": "Graphcore", "description": "AI intelligence processing units"},
    {"domain": "d-matrix.ai", "company_name": "d-Matrix", "description": "AI inference chips"},
    {"domain": "tenstorrent.com", "company_name": "Tenstorrent", "description": "AI computing hardware"},
    {"domain": "mythic.ai", "company_name": "Mythic AI", "description": "Analog compute for edge AI"},
    {"domain": "hailo.ai", "company_name": "Hailo", "description": "AI inference chip for edge devices"},
    {"domain": "kneron.com", "company_name": "Kneron", "description": "Edge AI chip company"},
    {"domain": "eta-compute.com", "company_name": "Eta Compute", "description": "Ultra-low power AI chips"},
    {"domain": "syntiant.com", "company_name": "Syntiant", "description": "Neural network chips for edge AI"},
    {"domain": "innatera.com", "company_name": "Innatera", "description": "Neuromorphic AI chips"},
    {"domain": "brainchip.com", "company_name": "BrainChip", "description": "Neuromorphic AI hardware"},
    {"domain": "gyrfalcon.ai", "company_name": "Gyrfalcon", "description": "Edge AI chips"},
    {"domain": "efinix.com", "company_name": "Efinix", "description": "FPGA for edge AI"},
    {"domain": "latticesemi.com", "company_name": "Lattice Semiconductor", "description": "Low-power FPGA for edge AI"},
]

all_companies = (
    [dict(c, source="ross-index-2024") for c in ross_2024]
    + [dict(c, source="product-hunt-devtools") for c in product_hunt_devtools]
    + [dict(c, source="framework-startups") for c in framework_startups]
)

# Deduplicate by domain
seen_in_run = set()
new_entries = []
already_exists = 0
new_count = 0

ts = datetime.now(timezone.utc).isoformat()

for c in all_companies:
    domain = normalize_domain(c.get("domain", ""))
    if not domain:
        continue
    if domain in seen_in_run:
        continue
    seen_in_run.add(domain)
    
    if is_new(domain):
        new_entries.append({
            "domain": domain,
            "company_name": c.get("company_name", ""),
            "source": c.get("source", "unknown"),
            "description": c.get("description", ""),
            "timestamp": ts,
        })
        new_count += 1
    else:
        already_exists += 1

print(f"\nBatch 2 Results:")
print(f"  Total candidates: {len(all_companies)}")
print(f"  Already in pipeline/queued: {already_exists}")
print(f"  NEW companies: {new_count}")

if new_entries:
    append_to_queue(new_entries)
    print(f"  Written to queue: {new_count} entries")

print(f"\nSample new domains:")
for e in new_entries[:20]:
    print(f"  {e['domain']} — {e['company_name']} [{e['source']}]")
