#!/usr/bin/env python3
"""Batch 4: AI startups, Built In companies, more topstartups, Otta, search results."""
import json, os
from urllib.parse import urlparse

EXISTING = "/Users/corgi12/.eragon-joshua_augustine/joshua_augustine_workspace/jordan.ai/sourcing/shared/existing_domains.txt"
OUTPUT = "/Users/corgi12/.eragon-joshua_augustine/joshua_augustine_workspace/jordan.ai/sourcing/wave2/jobboard_domains.jsonl"

with open(EXISTING) as f:
    existing = set(line.strip().lower() for line in f if line.strip())
written = set()
if os.path.exists(OUTPUT):
    with open(OUTPUT) as f:
        for line in f:
            try: written.add(json.loads(line)['domain'].lower())
            except: pass

added = 0
def add(domain, name, source="topstartups", category="saas", metadata=None):
    global added
    d = domain.lower().strip()
    if d.startswith('www.'): d = d[4:]
    d = d.split('/')[0].split('?')[0]
    if not d or d in existing or d in written: return
    with open(OUTPUT, 'a') as f:
        f.write(json.dumps({"domain": d, "name": name, "source": source, "category": category, "metadata": metadata or {}}) + '\n')
    written.add(d)
    added += 1

# AI Startups pages 2-5
ai_startups = [
    ("infinitus.ai", "Infinitus"),
    ("nooks.ai", "Nooks"),
    ("worldlabs.ai", "World Labs"),
    ("ssi.inc", "SSI"),
    ("together.ai", "Together AI"),
    ("sema4.ai", "Sema4.ai"),
    ("heygen.com", "HeyGen"),
    ("fireworks.ai", "Fireworks AI"),
    ("cognition-labs.com", "Cognition"),
    ("langchain.com", "LangChain"),
    ("instawork.com", "Instawork"),
    ("pika.art", "Pika"),
    ("airspace-intelligence.com", "Airspace Intelligence"),
    ("mistral.ai", "Mistral AI"),
    ("memorahealth.com", "Memora Health"),
    ("mindsdb.com", "MindsDB"),
    ("golden.com", "Golden"),
    ("aisera.com", "Aisera"),
    ("marqvision.com", "MarqVision"),
    ("builtrobotics.com", "Built Robotics"),
    ("viz.ai", "Viz.ai"),
    ("deepcellbio.com", "Deepcell"),
    ("salt.security", "Salt Security"),
]

# Built In companies (pages 1-3)
builtin = [
    ("clicktherapeutics.com", "Click Therapeutics"),
    ("tulip.co", "Tulip"),
    ("steelseries.com", "SteelSeries"),
    ("disqo.com", "DISQO"),
    ("forwardfinancing.com", "Forward Financing"),
    ("osohq.com", "Oso"),
    ("assembled.com", "Assembled"),
    ("empathy.com", "Empathy"),
    ("sortly.com", "Sortly"),
    ("unanet.com", "Unanet"),
    ("coreweave.com", "CoreWeave"),
    ("sailorhealth.com", "Sailor Health"),
    ("yooz.com", "Yooz"),
    ("rhymetec.com", "Rhymetec"),
    ("flourish.com", "Flourish"),
    ("catalant.com", "Catalant"),
    ("growtherapy.com", "Grow Therapy"),
    ("caxy.com", "Caxy"),
    ("imprivata.com", "Imprivata"),
    ("archsys.io", "Arch Systems"),
    ("stratadecision.com", "Strata Decision"),
    ("jumpcloud.com", "JumpCloud"),
    ("logicmonitor.com", "LogicMonitor"),
    ("vannevarlabs.com", "Vannevar Labs"),
    ("grail.com", "GRAIL"),
    ("sierraspace.com", "Sierra Space"),
    ("bounteous.com", "Bounteous"),
    ("ellevationeducation.com", "Ellevation Education"),
    ("webflow.com", "Webflow"),
    ("fusionrm.com", "Fusion Risk Management"),
    ("sparkadvisors.com", "Spark Advisors"),
    ("mabl.com", "mabl"),
]

# Otta companies
otta = [
    ("rollbar.com", "Rollbar"),
    ("tonkean.com", "Tonkean"),
    ("onfleet.com", "Onfleet"),
    ("fluent.co", "Fluent"),
]

# More topstartups from various categories
more_topstartups = [
    ("rivan.com", "Rivan Industries"),
    ("joinpogo.com", "Pogo"),
    ("opal.dev", "Opal"),
    ("joyfulhealth.com", "Joyful Health"),
]

# Additional from web searches — B2B SaaS
more_saas = [
    ("notion.so", "Notion"),
    ("airtable.com", "Airtable"),
    ("figma.com", "Figma"),
    ("linear.app", "Linear"),
    ("loom.com", "Loom"),
    ("retool.com", "Retool"),
    ("ashbyhq.com", "Ashby"),
    ("ramp.com", "Ramp"),
    ("brex.com", "Brex"),
    ("mercury.com", "Mercury"),
    ("gusto.com", "Gusto"),
    ("deel.com", "Deel"),
    ("remote.com", "Remote"),
    ("oysterhr.com", "Oyster"),
    ("pilot.com", "Pilot"),
    ("plaid.com", "Plaid"),
    ("marqeta.com", "Marqeta"),
    ("toast.com", "Toast"),
    ("faire.com", "Faire"),
    ("canva.com", "Canva"),
    ("calendly.com", "Calendly"),
    ("gong.io", "Gong"),
    ("outreach.io", "Outreach"),
    ("clari.com", "Clari"),
    ("salesloft.com", "SalesLoft"),
    ("chorus.ai", "Chorus.ai"),
    ("mixmax.com", "Mixmax"),
    ("apollo.io", "Apollo"),
    ("clearbit.com", "Clearbit"),
    ("zoominfo.com", "ZoomInfo"),
    ("sentry.io", "Sentry"),
    ("postman.com", "Postman"),
    ("hashicorp.com", "HashiCorp"),
    ("grafana.com", "Grafana Labs"),
    ("datadoghq.com", "Datadog"),
    ("confluent.io", "Confluent"),
    ("cockroachlabs.com", "CockroachDB"),
    ("neon.tech", "Neon"),
    ("supabase.com", "Supabase"),
    ("railway.app", "Railway"),
    ("render.com", "Render"),
    ("fly.io", "Fly.io"),
    ("dbt.com", "dbt Labs"),
    ("fivetran.com", "Fivetran"),
    ("airbyte.com", "Airbyte"),
    ("dagster.io", "Dagster"),
    ("prefect.io", "Prefect"),
    ("snyk.io", "Snyk"),
    ("wiz.io", "Wiz"),
    ("lacework.com", "Lacework"),
    ("orca.security", "Orca Security"),
    ("semgrep.dev", "Semgrep"),
    ("tailscale.com", "Tailscale"),
    ("cloudflare.com", "Cloudflare"),
    ("fastly.com", "Fastly"),
    ("contentful.com", "Contentful"),
    ("sanity.io", "Sanity"),
    ("storyblok.com", "Storyblok"),
    ("prismic.io", "Prismic"),
    ("strapi.io", "Strapi"),
    ("auth0.com", "Auth0"),
    ("okta.com", "Okta"),
    ("onelogin.com", "OneLogin"),
    ("1password.com", "1Password"),
    ("bitwarden.com", "Bitwarden"),
    ("dashlane.com", "Dashlane"),
    ("lastpass.com", "LastPass"),
    ("segment.com", "Segment"),
    ("amplitude.com", "Amplitude"),
    ("heap.io", "Heap"),
    ("fullstory.com", "FullStory"),
    ("hotjar.com", "Hotjar"),
    ("pendo.io", "Pendo"),
    ("walkme.com", "WalkMe"),
    ("intercom.com", "Intercom"),
    ("zendesk.com", "Zendesk"),
    ("freshworks.com", "Freshworks"),
    ("helpscout.com", "Help Scout"),
    ("gladly.com", "Gladly"),
    ("kustomer.com", "Kustomer"),
    ("dixa.com", "Dixa"),
    ("ada.cx", "Ada"),
    ("forethought.ai", "Forethought"),
    ("qualified.com", "Qualified"),
    ("drift.com", "Drift"),
    ("vidyard.com", "Vidyard"),
    ("leandata.com", "LeanData"),
    ("chili-piper.com", "Chili Piper"),
    ("6sense.com", "6sense"),
    ("demandbase.com", "Demandbase"),
    ("bombora.com", "Bombora"),
    ("terminus.com", "Terminus"),
    ("sendoso.com", "Sendoso"),
    ("postal.io", "Postal.io"),
    ("reachdesk.com", "Reachdesk"),
    ("alyce.com", "Alyce"),
    ("lavender.ai", "Lavender"),
    ("copy.ai", "Copy.ai"),
    ("jasper.ai", "Jasper"),
    ("writesonic.com", "Writesonic"),
    ("runway.com", "Runway"),
    ("stability.ai", "Stability AI"),
    ("midjourney.com", "Midjourney"),
    ("anthropic.com", "Anthropic"),
    ("cohere.com", "Cohere"),
    ("adept.ai", "Adept"),
    ("character.ai", "Character.AI"),
    ("inflection.ai", "Inflection AI"),
    ("anyscale.com", "Anyscale"),
    ("modal.com", "Modal"),
    ("replicate.com", "Replicate"),
    ("huggingface.co", "Hugging Face"),
    ("weights-biases.com", "Weights & Biases"),
    ("neptune.ai", "Neptune.ai"),
    ("wandb.ai", "Weights & Biases"),
    ("comet.com", "Comet"),
    ("dvc.org", "DVC"),
    ("ray.io", "Ray"),
    ("pinecone.io", "Pinecone"),
    ("weaviate.io", "Weaviate"),
    ("qdrant.tech", "Qdrant"),
    ("chroma.com", "Chroma"),
    ("milvus.io", "Milvus"),
    ("zilliz.com", "Zilliz"),
    ("superb-ai.com", "Superb AI"),
    ("scale.com", "Scale AI"),
    ("labelbox.com", "Labelbox"),
    ("v7labs.com", "V7"),
    ("snorkel.ai", "Snorkel AI"),
    ("cleanlab.ai", "Cleanlab"),
    ("dataiku.com", "Dataiku"),
    ("databricks.com", "Databricks"),
    ("h2o.ai", "H2O.ai"),
    ("c3.ai", "C3.ai"),
    ("palantir.com", "Palantir"),
    ("thoughtspot.com", "ThoughtSpot"),
    ("domo.com", "Domo"),
    ("sisense.com", "Sisense"),
    ("looker.com", "Looker"),
    ("metabase.com", "Metabase"),
    ("preset.io", "Preset"),
    ("hex.tech", "Hex"),
    ("observable.com", "Observable"),
    ("streamlit.io", "Streamlit"),
    ("gradio.app", "Gradio"),
    ("deepnote.com", "Deepnote"),
    ("coda.io", "Coda"),
    ("monday.com", "monday.com"),
    ("asana.com", "Asana"),
    ("height.app", "Height"),
    ("shortcut.com", "Shortcut"),
    ("hive.com", "Hive"),
    ("smartsheet.com", "Smartsheet"),
    ("teamwork.com", "Teamwork"),
    ("basecamp.com", "Basecamp"),
    ("twist.com", "Twist"),
    ("threads.com", "Threads"),
    ("missiveapp.com", "Missive"),
    ("front.com", "Front"),
    ("spike.email", "Spike"),
    ("superhuman.com", "Superhuman"),
    ("hey.com", "Hey"),
    ("convertkit.com", "ConvertKit"),
    ("mailchimp.com", "Mailchimp"),
    ("sendgrid.com", "SendGrid"),
    ("postmarkapp.com", "Postmark"),
    ("customer.io", "Customer.io"),
    ("iterable.com", "Iterable"),
    ("braze.com", "Braze"),
    ("onesignal.com", "OneSignal"),
    ("pushowl.com", "PushOwl"),
    ("appcues.com", "Appcues"),
    ("userpilot.com", "UserPilot"),
    ("chameleon.io", "Chameleon"),
    ("userguiding.com", "UserGuiding"),
    ("tango.us", "Tango"),
    ("loom.com", "Loom"),
    ("screencastify.com", "Screencastify"),
    ("mmhmm.app", "mmhmm"),
    ("around.co", "Around"),
    ("gather.town", "Gather"),
    ("teamflow.com", "Teamflow"),
    ("remote.com", "Remote"),
    ("lattice.com", "Lattice"),
    ("rippling.com", "Rippling"),
    ("bamboohr.com", "BambooHR"),
    ("namely.com", "Namely"),
    ("hibob.com", "HiBob"),
    ("personio.com", "Personio"),
    ("factorial.co", "Factorial"),
    ("sapling.com", "Sapling"),
    ("lever.co", "Lever"),
    ("greenhouse.io", "Greenhouse"),
    ("ashbyhq.com", "Ashby"),
    ("dover.com", "Dover"),
    ("gem.com", "Gem"),
    ("hireez.com", "hireEZ"),
    ("seekout.com", "SeekOut"),
    ("eightfold.ai", "Eightfold"),
    ("pymetrics.ai", "Pymetrics"),
    ("harver.com", "Harver"),
    ("criteria.com", "Criteria"),
    ("testgorilla.com", "TestGorilla"),
    ("codility.com", "Codility"),
    ("hackerrank.com", "HackerRank"),
    ("codesignal.com", "CodeSignal"),
    ("karat.com", "Karat"),
    ("interviewing.io", "interviewing.io"),
    ("triplebyte.com", "Triplebyte"),
    ("hired.com", "Hired"),
    ("vettery.com", "Vettery"),
    ("a.team", "A.Team"),
    ("toptal.com", "Toptal"),
    ("andela.com", "Andela"),
    ("turing.com", "Turing"),
    ("crossover.com", "Crossover"),
    ("arc.dev", "Arc"),
    ("gun.io", "Gun.io"),
    ("x-team.com", "X-Team"),
    ("numbrs.com", "Numbrs"),
    ("n26.com", "N26"),
    ("monzo.com", "Monzo"),
    ("revolut.com", "Revolut"),
    ("wise.com", "Wise"),
    ("nubank.com.br", "Nubank"),
    ("chime.com", "Chime"),
    ("current.com", "Current"),
    ("dave.com", "Dave"),
    ("varo.com", "Varo"),
    ("sofi.com", "SoFi"),
    ("betterment.com", "Betterment"),
    ("wealthfront.com", "Wealthfront"),
    ("robinhood.com", "Robinhood"),
    ("webull.com", "Webull"),
    ("alpaca.markets", "Alpaca"),
    ("tradier.com", "Tradier"),
    ("drivewealth.com", "DriveWealth"),
    ("apex-fintech.com", "Apex Fintech"),
    ("velotax.com.br", "VeloTax"),
    ("carta.com", "Carta"),
    ("pulley.com", "Pulley"),
    ("ltse.com", "LTSE"),
    ("pipe.com", "Pipe"),
    ("capchase.com", "Capchase"),
    ("clearco.com", "Clearco"),
    ("arc.tech", "Arc"),
    ("founderpath.com", "Founderpath"),
    ("recur.cloud", "Recur"),
    ("chargebee.com", "Chargebee"),
    ("paddle.com", "Paddle"),
    ("fastspring.com", "FastSpring"),
    ("lemonssqueezy.com", "Lemon Squeezy"),
    ("gumroad.com", "Gumroad"),
    ("memberful.com", "Memberful"),
    ("patreon.com", "Patreon"),
    ("ko-fi.com", "Ko-fi"),
    ("buymeacoffee.com", "Buy Me a Coffee"),
]

for d, n in ai_startups:
    add(d, n, "topstartups", "ai")
for d, n in builtin:
    add(d, n, "builtin", "saas")
for d, n in otta:
    add(d, n, "otta", "saas")
for d, n in more_topstartups:
    add(d, n, "topstartups", "saas")
for d, n in more_saas:
    add(d, n, "web_search", "saas")

print(f"\nBatch 4 total new: {added}")
print(f"Total in output: {len(written)}")
