PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE email_templates (
    id                 TEXT PRIMARY KEY,
    name               TEXT NOT NULL UNIQUE,
    buyer_type         TEXT NOT NULL,          -- operator | lender | arranger | all
    subject            TEXT NOT NULL,
    body               TEXT NOT NULL,          -- Handlebars template with {{merge_fields}}
    sequence_position  INTEGER NOT NULL DEFAULT 1,   -- 1=cold intro, 2=followup1, 3=followup2, 4=breakup
    days_after_previous INTEGER NOT NULL DEFAULT 0,  -- days after previous sequence email
    created_at         TEXT NOT NULL DEFAULT (datetime('now'))
  );
INSERT INTO email_templates VALUES('a9b0959d-d728-4523-b421-aeac9684dfbe','Cold Intro — GPU Operator','operator','Reducing residual value risk on your GPU fleet',unistr('Hi {{contact_name}},\u000a\u000aI''ll keep this short.\u000a\u000aCorgi provides a residual value floor on data-center GPUs — the part of the underwriting that makes lenders nervous about hardware value at maturity (typically 3–5 years out).\u000a\u000a{{#if gpu_fleet_scale}}For an operator with a fleet like {{company_name}}''s — {{gpu_fleet_scale}} — this directly improves your cost of capital and gives lenders the comfort to offer better leverage, longer tenor, or tighter pricing.{{else}}For a GPU operator like {{company_name}}, this translates directly into a better debt structure: lower spread, longer tenor, or higher leverage — because lenders have a clear floor on collateral value.{{/if}}\u000a\u000aWe work with GPU owners and their lenders to make financing cleaner. Not adding complexity — removing the one piece that typically slows deals down.\u000a\u000aWorth a 20-minute call with our founders, Isaac and Josh, to see if this fits your current or upcoming financing plans?\u000a\u000aBest,\u000aCorgi Team'),1,0,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('633009a9-6f7f-49f2-99ff-ef8fd208290d','Cold Intro — Lender','lender','GPU collateral protection for your lending portfolio',unistr('Hi {{contact_name}},\u000a\u000aQuick intro: Corgi builds residual value solutions for data-center GPUs.\u000a\u000a{{#if contact_title}}As {{contact_title}} at {{company_name}}, you''re likely evaluating AI infrastructure credit opportunities where GPU collateral at maturity is one of the harder underwriting questions.{{else}}At {{company_name}}, you''re likely evaluating AI infrastructure credit where GPU collateral value at maturity is one of the harder underwriting questions.{{/if}}\u000a\u000aWe provide a residual value floor that removes that uncertainty — giving your IC a cleaner recovery assumption and more confidence to lend at better LTV.\u000a\u000aThe result: more GPU-backed loans deployed, with better downside protection built into the structure.\u000a\u000aOpen to a short call to see if this fits your current credit box?\u000a\u000aBest,\u000aCorgi Team'),1,0,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('cac02aba-dc27-4f99-9737-ede49ebca6ad','Cold Intro — Reinsurer/Arranger','arranger','GPU residual value — new specialty line opportunity',unistr('Hi {{contact_name}},\u000a\u000aI wanted to flag an emerging capacity opportunity we think is well-suited for {{company_name}}.\u000a\u000aThe GPU infrastructure market is crossing $100B in financed assets — and the core underwriting challenge is residual value at maturity. Lenders want to deploy into AI infra but need a clear floor on hardware value 3–5 years out. That''s where Corgi comes in.\u000a\u000aThe structure is analogous to automotive residual value programs — an asset class with a proven reinsurance track record — applied to data-center GPUs. The market is early, deal flow is growing, and there''s real capacity need from well-capitalised counterparties.\u000a\u000aOur founders, Isaac and Josh, are building out the reinsurance relationships now. Would it make sense to have a brief introductory call?\u000a\u000aBest,\u000aCorgi Team'),1,0,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('e922ad44-8941-491a-a6ad-0471169120f6','Follow-Up 1','all','Re: [original subject]',unistr('Hi {{contact_name}},\u000a\u000aFollowing up on my note from a few days ago — wanted to add one data point.\u000a\u000aGPU infrastructure lending is accelerating fast, but most credit structures still carry unmitigated residual value risk at maturity. Lenders who can price that risk cleanly are winning deals. Those who can''t are sitting on the sideline.\u000a\u000aCorgi addresses that exact gap. Happy to send a one-pager or set up a quick call if timing works.\u000a\u000aBest,\u000aCorgi Team'),2,3,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('92326c75-e84d-49cf-853c-07faf5b81454','Follow-Up 2','all','Quick question about {{company_name}}''s GPU strategy',unistr('Hi {{contact_name}},\u000a\u000aOne quick question: is residual value on GPU collateral something that''s come up in your financing conversations recently — either as a concern from lenders, or something you''re actively trying to manage?\u000a\u000aAsking because the answer shapes whether Corgi is immediately relevant to you or more of a future conversation.\u000a\u000aEither way, happy to connect.\u000a\u000aBest,\u000aCorgi Team'),3,7,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('4a6f8ed9-97c6-4e90-973e-64f1cebb02e2','Follow-Up 3 (Break-Up)','all','Closing the loop',unistr('Hi {{contact_name}},\u000a\u000aI''ll leave you alone after this — just wanted to close the loop properly.\u000a\u000aIf GPU residual value risk ever becomes a live issue for {{company_name}}''s financing, Corgi is the company to know. We''re early, the founders are accessible, and the structure is purpose-built for this problem.\u000a\u000aNo action needed. If timing ever shifts, my details are below.\u000a\u000aBest,\u000aCorgi Team'),4,14,'2026-03-23 00:25:00');
INSERT INTO email_templates VALUES('e1a98cf7-b2df-4e5e-8e62-6523223d47d7','Warm Intro','all','Introduction — Corgi x {{company_name}}',unistr('Hi {{contact_name}},\u000a\u000a{{#if referrer_name}}{{referrer_name}} suggested I reach out — thought there was a natural overlap between what Corgi is building and what {{company_name}} is working on.{{else}}We were connected through a mutual introduction and I wanted to follow up.{{/if}}\u000a\u000aCorgi provides residual value solutions for data-center GPUs — helping GPU owners and their lenders get a better debt structure by reducing future hardware value risk. The core benefit is capital efficiency: lower cost of debt, higher leverage, or longer tenor.\u000a\u000aGiven {{company_name}}''s position in the market, I think there''s a clear conversation to be had. Would love to introduce you to our founders, Isaac and Josh, for a 20-minute call at your convenience.\u000a\u000aBest,\u000aCorgi Team'),1,0,'2026-03-23 00:25:00');
COMMIT;
